### ISSUE TITLE
Make cache dependent on "env" OR allow dynamic customization of the cache key

### ISSUE THREAD

**Issue by LionsAd** [travis-ci/travis-ci#3023]
The cache is great, but unfortunately for different environment variables the cache runs into a race condition.

Test case:

    matrix:
      env:
        - JOB="A"
        - JOB="B"

- Job A: Waits 5 seconds and creates $CACHE_DIR/a.txt
- Job B: Waits 20 seconds Creates $CACHE_DIR/b.txt

Because Job A and B are running at the same time, but Job B takes longer, Job B wins.

So the cache now has:

$CACHE_DIR/b.txt

But then Job A overwrites the cache again.

With some luck it starts early and has the $CACHE_DIR/b.txt and then can add its a.txt, but because B runs afterwards it will still overwrite with only b.txt, etc.

That unfortunately limits the cache usage.

Is there any other thing I can do right now to use something else in the build matrix, which the cache key is dependent on?

**Comment by coderanger** [comment]
Another use case for this, it would be nice to be able to have a single Gemfile that checks/uses an env var to control the version of a single gem rather than making a handful of actual Gemfiles. Currently I have to do the latter or the bundler cache thrashes back and forth.

**Comment by cvrebert** [comment]
Duplicate of #4393?

**Comment by BanzaiMan** [comment]
Just a heads up: I deployed a fix to production about 10 minutes ago. Please observe how your caches are behaving, and report issues if you see any.

**Comment by BanzaiMan** [comment]
This has been deployed and documented.

**Comment by ctubbsii** [comment]
@BanzaiMan Do you have a link to the documentation?

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices

**Comment by ctubbsii** [comment]
From the docs, it looks like they explain how to use an env variable to use distinct caches for different tasks in a matrix build. However, there still does not appear to be a way to share caches across jobs (to make PRs reuse cached maven repository from previous PRs, for example).
