### ISSUE TITLE
iOS tests are failing: Timed out waiting 120 seconds for simulator to boot

### ISSUE THREAD

**Issue by nsuarezml** [travis-ci/travis-ci#3040]
When I try run the tests with xcodebuild I receive the next error: 
"iPhoneSimulator: Timed out waiting 120 seconds for simulator to boot, current state is 1"

There is a closed issue with this problem: https://github.com/travis-ci/travis-ci/issues/2829

**Comment by ashfurrow** [comment]
I'm unable to use `xctool` as well. Any idea what this could be? Really tripping me up: https://travis-ci.org/artsy/eidolon/builds/46096336#L821-L824

**Comment by aleffert** [comment]
I'm seeing this problem intermittently

**Comment by 0xced** [comment]
I’m seeing this issue with the [Xcode 7 image](https://travis-ci.org/kif-framework/KIF/jobs/83250876#L443). The same project works fine with the [Xcode 6.4 image](https://travis-ci.org/kif-framework/KIF/jobs/83218703).

**Comment by ashfurrow** [comment]
We saw this issue, but it resolved itself when we started using `xcodebuild build test` instead of `xcodebuild build` then `xcodebuild test`.

**Comment by 0xced** [comment]
I changed the command from `xcodebuild test` to `xcodebuild build test` but I still get the simulator timeout. I’m not surprised this did not solve the issue since `xcodebuild test` and `xcodebuild build test` are essentially the same commands as `build` is just implicit when running `test` only.

**Comment by 0xced** [comment]
So, I found a workaround! You must explicitly launch the simulator before running the tests. Here is what I added in my `.travis.yml` files:
```yml
script:
  - open -b com.apple.iphonesimulator
```

Unlike what’s suggested in [“iPhoneSimulator: Timed out waiting” – Solved](http://devopslog.com/2015/06/iphonesimulator-timed-out-waiting-solved/), there is no need to pass the exact simulator UUID as argument.

Enjoy! ✨

**Comment by supermarin** [comment]
@0xced you're my hero

**Comment by BanzaiMan** [comment]
Hello, everyone! Thanks for the discussion here. Looks like https://github.com/travis-ci/travis-ci/issues/3040#issuecomment-146700203 is a definitive answer to this problem. Could (any of) you confirm this? We'll add it to our documentation. (We also welcome PR!)

**Comment by larslockefeer** [comment]
@BanzaiMan Unfortunately, it does not work for me when I leave out a specific UDID. Using the following fails:

```
script:
  - open -b com.apple.iphonesimulator
  - set -o pipefail
  - xcodebuild -project Picnic.xcodeproj -scheme Picnic -sdk iphonesimulator -destination "OS=9.1,name=iPhone 6" clean build | xcpretty -c || true
  - xcodebuild -project Picnic.xcodeproj -scheme Picnic -sdk iphonesimulator -destination "OS=9.1,name=iPhone 6" test | xcpretty -c
```

If I do add the UDID, everything works as expected. In order to decrease the possibilities of issues as described in #4906, I now do the following:

```
before_install:
  - SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6 (9.1) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")

script:
  - echo $SIMULATOR_ID
  - open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
  - set -o pipefail
  - xcodebuild -project Picnic.xcodeproj -scheme Picnic -sdk iphonesimulator -destination "OS=9.1,name=iPhone 6" clean build | xcpretty -c || true
  - xcodebuild -project Picnic.xcodeproj -scheme Picnic -sdk iphonesimulator -destination "OS=9.1,name=iPhone 6" test | xcpretty -c
```

**Comment by ohadschn** [comment]
@larslockefeer I'm experiencing the same. In our case we're using the latest SDK so instead of specifying the version I say: `SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6 \(.*\) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")`.

**Comment by marcdown** [comment]
@larslockefeer your solution worked for me - thanks!

**Comment by guidomb** [comment]
I am still seeing this issue non of the solutions proposed here worked.

**Comment by ricardopereira** [comment]
What about using [scan](https://github.com/fastlane/scan)?
Maybe it could help.

**Comment by larslockefeer** [comment]
@guidomb The solution that I proposed is working flawlessly for me. What did you try? Maybe I can help to resolve your issue?

**Comment by bgerstle** [comment]
ditto, we're using [the approach](https://github.com/wikimedia/wikipedia-ios/blob/master/.travis.yml#L13) suggested by @larslockefeer and haven't seen the timeout since. an add'l refinement is that we're running a [matrix of builds](https://github.com/wikimedia/wikipedia-ios/blob/master/.travis.yml#L3) and are setting an env var for the different versions of the simulator to be used.

**Comment by guidomb** [comment]
@larslockefeer I tried what you said. I was having an issue with your bash line because it was returning multiple UUID so I refactored it into a Ruby script (which works) but I keep getting timeouts

```ruby
#!/usr/bin/env ruby

simulator_name = ARGV[0]
simulator_version = ARGV[1] || "latest"

raise "simulator name is required" unless simulator_name

destinations = STDIN.readlines
  .select { |destination| destination.start_with?("#{simulator_name} ") }
  .map { |destination| destination.strip }

simulator =
  if simulator_version == "latest"
    destinations.last
  else
    destinations.select do |destination|
      match = destination.match(/^#{simulator_name} \((\d+\.\d+(\.\d+)?)\) .*$/)
      match[1] == simulator_version
    end
    .first
  end
uuid = simulator.match(/^.*\[(.*)\]$/)[1]

if uuid
  puts uuid
else
  puts "Cannot find simulator UUID for #{simulator_name} (#{simulator_version})"
  exit 1
end
```

**Comment by guidomb** [comment]
I pretty sure that for some reason the VM is out of CPU resource my build time started to go from 8 minutes to 15 minutes and then I started to see timeouts. Maybe is related somehow.

**Comment by guidomb** [comment]
OK my assumption was incorrect. There is a bug in `xcodebuild` which has been fixed in the latest release of XCode, `7.2.1` (which was released an hour ago). From the release notes

> Fixed in Xcode 7.2.1:
>
>• Command line tool ‘xcodebuild test’ will no longer time out waiting for Simulator.app to launch

**Comment by gsabran** [comment]
FYI I'm having the same issue with Xcode 8.3. I'm trying to debug a failing build using the debug options that lets me ssh into the VM. There, I'm running

```bash
pod install

SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone SE (10.3) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")
open -a Simulator --args -CurrentDeviceUDID $SIMULATOR_ID
echo $SIMULATOR_ID
# 3C358901-B375-4F3E-87D9-B7FF56CBEFE5

xcodebuild \
  -workspace MyApp.xcworkspace \
  -scheme MyApp \
  -sdk iphonesimulator \
  -destination "platform=iOS Simulator,name=iPhone SE,OS=10.3" \
  -derivedDataPath './test-outputs' \
  build test | xcpretty --test
```
After a while this prints:

```
xcodebuild[19500:54347] [MT] IDETestOperationsObserverDebug: (6F259D81-9A50-4255-BDA2-258868D706B7) Failed to make test runner session:
Error Domain=com.apple.dt.xctest.error Code=7 "Timed out waiting 120 seconds for simulator to boot, current state is 1." UserInfo={NSLocalizedDescription=Timed out waiting 120 seconds for simulator to boot, current state is 1.}
xcodebuild[19500:54347] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Timed out waiting 120 seconds for simulator to boot, current state is 1. If you believe this error represents a bug, please attach the log file at /Users/travis/build/team-pie/pie-ios/test-outputs/Logs/Test/1690D27F-3014-4938-BE67-9B013D03A865/Session-UI-Tests-2017-04-05_235125-lD8g6t.log" UserInfo={NSLocalizedDescription=Timed out waiting 120 seconds for simulator to boot, current state is 1. If you believe this error represents a bug, please attach the log file at /Users/travis/build/my-username/my-repo/test-outputs/Logs/Test/1690D27F-3014-4938-BE67-9B013D03A865/Session-UI-Tests-2017-04-05_235125-lD8g6t.log}
```

The referenced output file reads:

```
23:51:25.635 xcodebuild[19500:54347] Beginning test session UI-Tests-6F259D81-9A50-4255-BDA2-258868D706B7 at 2017-04-05 23:51:25.634 with Xcode 8E162 on target <DVTiPhoneSimulator: 0x7f8e97059c10> {
                SimDevice: SimDevice : iPhone SE (3C358901-B375-4F3E-87D9-B7FF56CBEFE5) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-SE } runtime={ SimRuntime : 10.3 (14E269) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3 (14E269))
23:51:25.636 xcodebuild[19500:54347]    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
-workspace
MyApp.xcworkspace
-scheme
MyApp
-sdk
iphonesimulator
-destination
platform=iOS Simulator,name=iPhone SE,OS=10.3
-derivedDataPath
./test-outputs
build
test
23:51:25.636 xcodebuild[19500:54347] Launching with Xcode.IDEFoundation.Launcher.PosixSpawn
23:51:49.216 xcodebuild[19500:54347] Launch session started.
23:51:49.234 xcodebuild[19500:54347] Adding console adaptor <IDEConsoleAdaptor: 0x7f8e98404b80 'target'> for test session 6F259D81-9A50-4255-BDA2-258868D706B7.
23:51:49.239 xcodebuild[19500:56524] 3C358901-B375-4F3E-87D9-B7FF56CBEFE5: Registered for sim device notification, got token 5
23:53:37.571 xcodebuild[19500:57346] Timed out waiting 120 seconds for simulator to boot, current state is 1.
23:53:37.572 xcodebuild[19500:57346] Sim iPhone SE: Unregistering for sim device notification with token 4
23:53:37.572 xcodebuild[19500:57346] Error returned from opening test runner connection: Error Domain=com.apple.dt.xctest.error Code=7 "Timed out waiting 120 seconds for simulator to boot, current state is 1." UserInfo={NSLocalizedDescription=Timed out waiting 120 seconds for simulator to boot, current state is 1.}
23:53:37.572 xcodebuild[19500:54347] Failed to make test runner session:
Error Domain=com.apple.dt.xctest.error Code=7 "Timed out waiting 120 seconds for simulator to boot, current state is 1." UserInfo={NSLocalizedDescription=Timed out waiting 120 seconds for simulator to boot, current state is 1.}
23:53:37.572 xcodebuild[19500:54347] Test operation failure: Timed out waiting 120 seconds for simulator to boot, current state is 1.
23:53:37.572 xcodebuild[19500:54347] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Timed out waiting 120 seconds for simulator to boot, current state is 1." UserInfo={NSLocalizedDescription=Timed out waiting 120 seconds for simulator to boot, current state is 1.} didCancel: 1
```

**Comment by humblehacker** [comment]
@gsabran Did you ever get past this?  I'm running into the same issue with Travis CI and Xcode 8.3.

**Comment by gsabran** [comment]
nop I didn't solve the issue with the VM. I ended up uploading test outputs and screenshots to S3 and debug from there (it's extremely slow)

**Comment by laszloagardi** [comment]
I managed to work around this by first building the target then testing. It seems launching the simulator times out during building if I did this in one step. I used the following:

```
xcodebuild build -workspace "MyWorkspace.xcworkspace" -scheme "MyScheme" -sdk iphonesimulator -configuration Debug -derivedDataPath out/DerivedData -destination "platform=iOS Simulator,name=iPhone 7"
xcodebuild test  -workspace "MyWorkspace.xcworkspace" -scheme "MyScheme" -sdk iphonesimulator -configuration Debug -derivedDataPath out/DerivedData -destination "platform=iOS Simulator,name=iPhone 7,OS=10.1"
xcodebuild test  -workspace "MyWorkspace.xcworkspace" -scheme "MyScheme" -sdk iphonesimulator -configuration Debug -derivedDataPath out/DerivedData -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.3"
```

**Comment by getaaron** [comment]
I've had some improved success explicitly killing the simulator before opening it:

```bash
killall Simulator &> /dev/null
```

This way the explicit open will still work if Simulator is unresponsive.

Still doesn't work 100% of the time for some reason though.

**Comment by ollieatkinson** [comment]
```
open -a Simulator --args -CurrentDeviceUDID $(xcrun simctl list --json | ruby -e "require 'json'; puts JSON.parse(ARGF.read)['devices']['iOS 10.0'].find { |s| s['name'] == 'iPhone 6' }['udid']")
```

```
set -o pipefail && xcodebuild -derivedDataPath $(mktemp -d) -workspace AppName.xcworkspace -scheme AppScheme -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' test | xcpretty -c
```

You can tidy it up by writing some scripts, but placing those directly inside the travis YAML solved my issue with the timeouts.
