### ISSUE TITLE
Special cache directives (pip, bundler, ccache, etc.) depend on not overriding install

### ISSUE THREAD

**Issue by dstufft** [travis-ci/travis-ci#3239]
I'm told that if you override the ``install`` directive inside a ``.travis.yml`` that the ``cache: pip`` directive will just silently stop working. I'm not sure why this would be the case but I think that it shouldn't do that. ``cache: pip`` is just a short hand for ``cache: directories: ~/.cache/pip`` and it doesn't seem like it should be tied to the install command at all?

**Comment by thedrow** [comment]
Yup. See [build log](https://travis-ci.org/tomchristie/django-rest-framework/jobs/51048138#L100).
Nothing is cached after the installation.

**Comment by BanzaiMan** [comment]
`cache: pip` works while running the default `install` section. If you override it, we don't have a way to do it. I believe @dstufft and @joshk are working on improving this.

**Comment by dstufft** [comment]
Maybe I just don't understand how Travis caching works, but why is ``cache: pip`` tied to the default ``install`` section? Surely ``cache: pip`` is just a shortcut for ``cache: directories: ~/.cache/pip``?

**Comment by joshk** [comment]
You are pretty much right, and yet it is a bit more complicated than that.

We set up the cached dirs before running the default install commands, which means if you overwrite the defaults they dir won't be setup.

We have talked about changing this but don't have an ETA yet sorry.

**Comment by graingert** [comment]
@joshk can you update the docs to say that "even if you use pip in your install, any overriding disables the default pip cache"

**Comment by BanzaiMan** [comment]
We have rolled out a feature flip to opt in to test the fix.

To use, add `cache.custom_install: true`. If you are using `cache: bundler` right now, for example, change this to:

```yaml
cache:
  bundler: true
  custom_install: true
  ⋮
```

Once we have enough confidence that the fix is sound, it'll be available to everyone.

**Comment by thedrow** [comment]
Great to hear that! This is a long time problem with the feature. I'm glad that it will be resolved soon.

**Comment by BanzaiMan** [comment]
We will be testing the above PR (that eradicates the need `cache.custom_install` option) soon in staging. If you are interested in testing it, please set up a (perhaps special-purpose) repository on https://staging.travis-ci.org/.

I plan to start this tomorrow (HST).

**Comment by thedrow** [comment]
Wonderful! Great news.

**Comment by BanzaiMan** [comment]
My tests so far have been successful. Please test it while you can. I plan on rolling this out to production around 2016-02-16T15:00Z.

**Comment by BanzaiMan** [comment]
The PR has been deployed to production.

**Comment by BanzaiMan** [comment]
This has been deployed to production.

**Comment by graingert** [comment]
@BanzaiMan what went wrong the first time ;)?

**Comment by BanzaiMan** [comment]
@graingert In some cases (in Ruby), the default `install` command was run unnecessarily.

**Comment by skirpichev** [comment]
> If you are using cache: bundler right now, for example, change this to:
> cache:
>  bundler: true
>  custom_install: true

For pip, the "right way" now is:
```
cache:
  pip: true
  custom_install: true
```
?

I tried to use either this or just "cache: pip", and as a result (apart from caching doesn't
work) - these tracebacks in the end:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/109716280/log.txt
https://s3.amazonaws.com/archive.travis-ci.org/jobs/109648431/log.txt
E.g.:
```
/home/travis/.casher/bin/casher:136:in `read': No such file or directory - /home/travis/.casher/paths (Errno::ENOENT)
	from /home/travis/.casher/bin/casher:136:in `changed?'
	from /home/travis/.casher/bin/casher:109:in `push'
	from /home/travis/.casher/bin/casher:52:in `block in run'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
	from /home/travis/.casher/bin/casher:52:in `run'
	from /home/travis/.casher/bin/casher:226:in `<main>'
```

**Comment by BanzaiMan** [comment]
@skirpichev Those are builds from the time that the fix was not in place. Could you restart them now?

**Comment by skirpichev** [comment]
First, "cache: pip" should be enough?

**Comment by BanzaiMan** [comment]
@skirpichev Yes, now.

**Comment by skirpichev** [comment]
Ok, done in https://github.com/skirpichev/omg/pull/222

**Comment by BanzaiMan** [comment]
The PR has been merged and deployed. We had some issues in production, but I believe they have been fixed as well. I'm closing this issue. If you see problems—a build with custom `install` and special `cache` directives does not cache correctly—do open a new issue, please.

**Comment by tbarbugli** [comment]
we have a custom install section and this to store cache:

```
cache:
  apt: true 
  directories:
    - $HOME/.cache/pip
    - $HOME/build/xxx/yyy/node_modules
```

it worked fine for a few weeks but we not get this error at the end of the build:

```
/home/travis/.casher/bin/casher:136:in `read': No such file or directory - /home/travis/.casher/paths (Errno::ENOENT)
    from /home/travis/.casher/bin/casher:136:in `changed?'
    from /home/travis/.casher/bin/casher:109:in `push'
    from /home/travis/.casher/bin/casher:52:in `block in run'
    from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
    from /home/travis/.casher/bin/casher:52:in `run'
    from /home/travis/.casher/bin/casher:226:in `<main>'
```

what's the right way to fix this?

**Comment by BanzaiMan** [comment]
@tbarbugli Since you are not using the special `cache` directives (such as `cache: pip`), your error is unrelated to this issue. I see that you sent us support email, so we'll continue troubleshooting there.

**Comment by aandis** [comment]
I was still facing this issue with 
```
cache:
    bundler: true
```
I removed the overridden `install` directive in `.travis.yml` and caching started working.

**Comment by BanzaiMan** [comment]
@aandis Do you have a build log URL that shows the problem you are describing here? Do keep in mind that `bundler: true` is effective only for Ruby builds.

**Comment by aandis** [comment]
I can't find the build log right now but I can describe what the problem was. In my install directive I had-

```yaml
install
  - bundle install
  - npm install
```

The `bundle install` is there because I was facing https://github.com/bundler/bundler/issues/5068#issuecomment-260182993. I moved the `npm install` to `before_install` directive and removed `install` directive which surprisingly fixed https://github.com/bundler/bundler/issues/5068 and made caching work.

**Comment by BanzaiMan** [comment]
@aandis Overriding `install` does not affect whether or not caching is effective, so I am surprised to read what you are describing.
