### ISSUE TITLE
Artifacts env setting are incorrectly overridden

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/travis-ci#3432]
e.g. if `ARTIFACTS_PATHS` is set in the environment but _not_ at `addons.artifacts.paths`, then the default value of `ARTIFACTS_PATHS="$(git ls-files -o | tr "\n" ":")"` is exported.  Additionally, the paths appear to be passed as positional arguments, which results in errors like:

```
$ artifacts upload
/home/travis/build.sh: line 41: /home/travis/bin/artifacts: Argument list too long
/home/travis/build.sh: line 73: /bin/uname: Argument list too long
/home/travis/build.sh: line 81: /bin/date: Argument list too long
/home/travis/build.sh: line 65: -: syntax error: operand expected (error token is "-")
```

**Comment by lekshmideepu** [comment]
I also came across the same error:

Uploading Artifacts (BETA)
$ travis_artifacts_install
artifacts version v0.7.8-9-g0908379 revision=09083791933418ce154332d7ef83bdee4330adb8
$ export ARTIFACTS_PATHS="$(git ls-files -o | tr \"\\n\" \":\")"
/home/travis/build.sh: line 73: /bin/uname: Argument list too long
/home/travis/build.sh: line 81: /bin/date: Argument list too long
$ artifacts upload
/home/travis/build.sh: line 41: /home/travis/bin/artifacts: Argument list too long
/home/travis/build.sh: line 73: /bin/uname: Argument list too long
/home/travis/build.sh: line 81: /bin/date: Argument list too long
/home/travis/build.sh: line 65: -: syntax error: operand expected (error token is "-")
Done uploading artefacts

I tried declaring  ARTIFACTS_TARGET_PATHS in the  env:global part as given below:
  ARTIFACTS_TARGET_PATHS="artifacts/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER:artifacts/$TRAVIS_COMMIT"
Also set the  addons:  artifacts: true 
Still getting the same error message given above. 
Any help will be very much appreciated!

**Comment by BanzaiMan** [comment]
@meatballhat Could you take a look at this soon? Thanks.

**Comment by meatballhat** [comment]
The version of `artifacts` being used in production now (via travis-build) is `v0.7.8-25-ge2af40f`, which includes some changes meant to address this issue.  For anyone still experiencing issues, pretty please post URLs or job output :heart_eyes_cat:

**Comment by proppy** [comment]
@meatballhat I still have some issue with artefacts

https://travis-ci.org/googlesamples/android-ndk/builds
https://s3.amazonaws.com/archive.travis-ci.org/jobs/97599159/log.txt
```
[33;1mUploading Artifacts (BETA)[0m
travis_fold:start:artifacts.setup
[0Kartifacts version v0.7.8-25-ge2af40f revision=e2af40fea0aa0229ff1f26e932e018c71e95bb91
$ export ARTIFACTS_PATHS="$(git ls-files -o | tr \"\\n\" \":\")"
travis_fold:end:artifacts.setup
[0K$ artifacts upload
/home/travis/build.sh: line 45: /home/travis/bin/artifacts: Argument list too long
[33;1mDone uploading artifacts[0m
```

**Comment by adilansari** [comment]
@meatballhat Still seeing the issue
https://travis-ci.org/fit360/spott/builds/119181267

**Comment by meatballhat** [comment]
I'm closing this out given that the version of artifacts in production has since been updated.  Please yell (with job URLs) if you're still seeing issues.  :heart:

**Comment by olivierlacan** [comment]
@meatballhat Still having this issue with repository setting env vars.

They print correctly at the top of the build: 

```yaml
$ export ARTIFACTS_PATHS="logs/test.log"
```

Despite that:

```
Uploading Artifacts (BETA)
artifacts.setup
artifacts version v0.7.8-26-gd62580b revision=d62580ba6bfffc7245d8ac6a1a384ef60b9302e7
$ export ARTIFACTS_PATHS="$(git ls-files -o | tr \"\\n\" \":\")"
$ artifacts upload
/home/travis/build.sh: line 62: /home/travis/bin/artifacts: Argument list too long
Done uploading artifacts
```

It appears that it's ignoring any previously set `ARTIFACTS_PATHS` env var. Going to try the YAML way.
