### ISSUE TITLE
/home/travis/build.sh: line 175: brew: command not found

### ISSUE THREAD

**Issue by andyli** [travis-ci/travis-ci#3448]
Since 3 hours ago, the OSX builds have been failing with the error:
```
/home/travis/build.sh: line 175: brew: command not found
```

An example build can be found at https://travis-ci.org/HaxeFoundation/haxe/builds/55650892

**Comment by andyli** [comment]
The build log starts with `Using worker: worker-linux-08b40318-1.bb.travis-ci.org:travis-linux-14`, so it seems it is using a wrong worker (linux instead of mac).
Note that the haxe repo has multi-os enabled long time ago.

**Comment by henrikhodne** [comment]
Thanks for raising this! We changed our queueing logic earlier today, which seems to have affected multi-os jobs. We've fixed the bug now, but unfortunately the queue (and therefore worker type) is assigned when the request comes from GitHub, so restarting the job won't help in fixing this. Any new commits should go to the OS X workers again, though.

**Comment by andyli** [comment]
I confirm the new builds are normal now. Thanks!
BTW, I hope multi-os will be generally available soon, since we've a few more repos would be benefited :)

**Comment by epwalsh** [comment]
I am having a similar problem, I am just trying to build on os x yet the build seems to be reverting to linux. This is my .travis.yml:

```
language: cpp
os: osx
compiler: 
  - clang 
before_install:
  - brew update 
  - brew install boost 
script: 
  - make
notifications:
  - email:
    on_success: change
    on_failure: change
```

**Comment by denfromufa** [comment]
I'm still having this issue, see this build of pythonnet:

https://travis-ci.org/pythonnet/pythonnet/jobs/163304757#L1892

**Comment by andyli** [comment]
Your linked build log is using linux (correctly), so brew is missing as expected.
There is something wrong with the `before_install` command though as I can see apt-get is run as well as brew... Maybe it is too complex for Travis to process or there is just some hidden typo.

Try separate the commands as follows:
```
before_install: 
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    brew update;
    brew install mono;
    brew install pyenv;
    pyenv install $PYTHON;
    fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe";
    sudo apt-get install software-properties-common;
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF;
    echo "deb http://download.mono-project.com/repo/debian wheezy/snapshots/4.2.4.4 main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list;
    echo "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list;
    sudo apt-get update;
    sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install mono-devel mono-complete referenceassemblies-pcl ca-certificates-mono nunit-console;
    fi
```

See what will happen.

**Comment by denfromufa** [comment]
@andyli thanks for suggestion! still the same error though:

https://travis-ci.org/pythonnet/pythonnet/jobs/163311291#L130

**Comment by andyli** [comment]
That's a different error. No?

brew prefer a newer osx version, so let's use `osx_image: xcode6.4` as documented at 
https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version

**Comment by denfromufa** [comment]
@andyli sorry I meant to post that error in this thread:

https://github.com/Homebrew/brew/issues/1175

Too many issues trying to work at the same time with travis ci, osx & linux, python, brew, mono, tox, pyenv!
