### ISSUE TITLE
My repository cannot be found through travis cli

### ISSUE THREAD

**Issue by alansouzati** [travis-ci/travis-ci#4017]
Hi,

  I've just changed my repository from private to public. Now whenever I'm trying to use the travis cli command I get the following error:

> repository not known to https://api.travis-ci.com/: HewlettPackard/grommet

The repo exists and I don't know what I'm doing wrong. I'm trying to execute a `travis encrypt` to integrate Travis with Slack.

Kr,
Alan

**Comment by drogus** [comment]
@alansouzati: could you try again now? A few DB updates introduce a problem that might return the wrong repository for some of the queries if the repository has duplicates (which might happen in some cases, for example when you delete and then recreate a repository). It should be fixed now, although we're not sure if we covered all of the cases.

**Comment by alansouzati** [comment]
Hi @drogus, Thanks for the quick follow up on this. However I'm afraid I'm still having the same issue. I've even reinstalled travis gem (1.7.7).

```
Detected repository as HewlettPackard/grommet, is this correct? |yes| yes
repository not known to https://api.travis-ci.com/: HewlettPackard/grommet
```

**Comment by BanzaiMan** [comment]
@alansouzati I looked at the data, and found that the repository is known, but there is no admin user associated with it, and therefore you cannot access it. Do you know anyone who does?

**Comment by alansouzati** [comment]
Hey @BanzaiMan, I'm not sure I get what you mean. Admin user in Github side or Travis side? We used to have Travis PRO associated with this repo when it was private. Now it is public and I'm assuming the subscription has been cancelled?

**Comment by alansouzati** [comment]
I'm in the Grommet core team, so I have full access to the organization.

**Comment by BanzaiMan** [comment]
Ah. It's public now. I somehow overlooked this critical detail. Then I believe you are talking to a wrong API endpoint. Tack on `--org` to your `travis` command and I believe it'll work.

**Comment by alansouzati** [comment]
Awesome. It works! Sorry for wasting your time :disappointed:

**Comment by BanzaiMan** [comment]
No worries. I'm happy to know it's working for you now.
