### ISSUE TITLE
No input files were specified for target GenerateSatelliteAssemblies, skipping

### ISSUE THREAD

**Issue by fredatgithub** [travis-ci/travis-ci#4628]
Hello,
I have a GitHub repository:
https://github.com/fredatgithub/chronometre
The build fails every time despite compiling ok on Visual Studio.
I have this error:
No input files were specified for target GenerateSatelliteAssemblies, skipping
How can I specify this target GenerateSatelliteAssemblies ?

**Comment by BanzaiMan** [comment]
cc @joshua-anderson @akoeplinger @nterry

**Comment by fredatgithub** [comment]
I've created an empty VB.NET project with no code and try to compile it and it fails 
The error message I've got is that the System.Deployment DLL is not resolved by Travis which is by default in a VB.NET Windows Application template.
So i've deleted the DLL and tried again: it fails

**Comment by fredatgithub** [comment]
The empty VB.NET project is
https://github.com/fredatgithub/VB.Net_Travis_Test

**Comment by fredatgithub** [comment]
Changing target framework 4.0 for 4.5
Travis build fails

**Comment by fredatgithub** [comment]
Trying to build the project instead of the solution by adding in the .travis.yml file:
script:
 - xbuild /p:Configuration=Release WindowsApplicationTravisDemo/WindowsApplicationTravisDemo.vbproj
it fails again

**Comment by fredatgithub** [comment]
As you can see in this file:
https://github.com/fredatgithub/VB.Net_Travis_Test/blob/master/WindowsApplicationTravisDemo/Form1.vb
There is no code, this is the simplest VB.NET Windows Application template and it doesn't build with Travis.

**Comment by akoeplinger** [comment]
Hey, sorry for the delay, I missed this issue. You're running into a bug with the VB setup under Mono 4.0 that is fixed in the upcoming Mono 4.2 release.

Please change your script to: "xbuild /p:VbcToolExe=vbnc.exe WindowsApplicationTravisDemo.sln" and it'll work.

Sorry for the confusion, but VB.NET is a "best effort" kind of thing in Mono until Mono switches to the new Roslyn compiler platform.

**Comment by fredatgithub** [comment]
Thanks for the answer even late it's better than no answer.
I don't develop in VB.NET anymore, I've switched to C# but I've got old applications still being used.
I know that you're answering on a best effort basis, I don't complain, I appreciate a lot this CI service.
Thanks for what you do.

**Comment by fredatgithub** [comment]
Hello,
I've applied this solution to another VB.NET project:
https://github.com/fredatgithub/chronometre
and it doesn't build
Is there another bug in Mono 4.0?

**Comment by akoeplinger** [comment]
@fredatgithub I got it to build by removing Shared from [FormMain.vb#L59](https://github.com/fredatgithub/chronometre/blob/56c8825b62eedfcd594474b13dc8071ddfb2111b/Chronometre/FormMain.vb#L59) and line 71. I'm not familiar with VB though, so no idea what that does :smile:

**Comment by fredatgithub** [comment]
I've removed shared keyword and it still doesn't build as you can see in the log :O(
https://travis-ci.org/fredatgithub/chronometre

**Comment by akoeplinger** [comment]
@fredatgithub hmm, it says the commit it built is https://github.com/fredatgithub/chronometre/commit/88a70c4fbbab074e303f5e91f0db3993941c351a, which is 10 days old? did you disable Travis somehow?

**Comment by fredatgithub** [comment]
Yes I gave up and disabled Travis but just turn it back on recently.

**Comment by akoeplinger** [comment]
Can you try pushing another commit to your repository? Clicking "Restart Job" on Travis doesn't work since that only builds the old commit.

**Comment by fredatgithub** [comment]
Ok it's done

**Comment by akoeplinger** [comment]
Travis didn't notice it. Are you sure you've reactivated it correctly?

**Comment by fredatgithub** [comment]
You're right
I've just commit and the log doesn't show the commit
https://travis-ci.org/fredatgithub/chronometre/builds

**Comment by fredatgithub** [comment]
Build pushes was off and I've just turned it on

**Comment by fredatgithub** [comment]
I've just committed one more time and it works fine
hurray
thanks for your help

**Comment by akoeplinger** [comment]
:+1: :smile:
