### ISSUE TITLE
Intermittent iOS build failure: “Connection peer refused channel request”

### ISSUE THREAD

**Issue by pcantrell** [travis-ci/travis-ci#4725]
On Xcode 7 beta, while Travis was running this command:

    xcodebuild test -project Siesta.xcodeproj -scheme Siesta -destination 'platform=iOS Simulator,name=iPhone 5s' | xcpretty -c

…it gave this output:

    2015-08-31 17:46:56.409 xcodebuild[616:2926] [MT] IDETestOperationsObserverDebug: (C1F29FCB-139E-4221-95EF-080A81985FBC) Beginning test session with Xcode 7A192o on target <DVTiPhoneSimulator: 0x7ffce1d669e0> {
            SimDevice: SimDevice : iPhone 5s (91811508-C774-4679-84C2-EA9634E09DEB) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-5s } runtime={ SimRuntime : 9.0 (13A4325c) - com.apple.CoreSimulator.SimRuntime.iOS-9-0 }
    } (9.0 (13A4325c))
    ▸ Building Siesta/Siesta [Debug]
    2015-08-31 17:48:12.592 xcodebuild[616:3137] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7ffce1f03ef0>
    ▸ Compiling Siesta_vers.c
    ▸ Linking Siesta
    ▸ Copying Siesta.h
    ▸ Compiling ResourceStatusOverlay.xib
    ▸ Processing Info.plist
    ▸ Touching Siesta.framework
    ▸ Building Siesta/SiestaTests [Debug]
    ▸ Processing Info.plist
    ▸ Compiling ObjcCompatibilitySpec.m
    ▸ Compiling SiestaTests_vers.c
    ▸ Linking SiestaTests
    ▸ Copying Carthage/Build/iOS/Nimble.framework
    ▸ Copying Carthage/Build/iOS/Quick.framework
    ▸ Copying Carthage/Build/iOS/Nocilla.framework
    ▸ Copying Carthage/Build/iOS/Alamofire.framework
    ▸ Touching SiestaTests.xctest
    ** TEST FAILED **

…and the build failed.

After restarting the build from the Travis CI admin interface (i.e. no changes to project), the build succeeded.

The project in question is [bustoutsolutions/siesta](https://github.com/bustoutsolutions/siesta).

**Comment by pcantrell** [comment]
Happening repeatedly, but intermittently.

**Comment by pcantrell** [comment]
Still happening with the Xcode 7 GM, alas.

**Comment by pcantrell** [comment]
Hadn’t seen this for a while, so I added the Travis badge to my project — and the push that added that badge exhibited the bug:

https://travis-ci.org/bustoutsolutions/siesta/builds/82994210

IRONY.

**Comment by pcantrell** [comment]
Perhaps this is a clue, perhaps it is a different bug…

This Travis build failed where it should have succeeded:

https://travis-ci.org/bustoutsolutions/siesta/builds/83745161

(The previous build succeeded, and the only difference was a change to a couple of comments, so … false negative.)

At the bottom I notice Quick saying that it only executed 90 specs; however, in the log output, there are 227 check marks indicating specs passed. Is Travis perhaps running specs in a concurrent mode or something that might expose a race condition in Quick?

**Comment by mattyohe** [comment]
@pcantrell Ooo! Thank you for catching this. I have been experiencing similar puzzling issues on a private repo, random ** Test Failed ** occurrences, but no visible tests appear to have failed. I also didn't have xcpretty wired up on this yet, so I had not noticed what you pointed out:
 `Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7f8882bf9030>`

But I just did a quick search and found the above in one of the "failing" builds.

I'll try to figure out what's going on, but just for some additional information here, this is on a very simple "test" occurring using this:
```bash
xcodebuild test -workspace $XCWORKSPACE -scheme $XCSCHEME  -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
```

**Comment by pcantrell** [comment]
@mattyohe Glad I'm not the only one.

I noticed that in my log output, the “Executed XX tests” counts are wrong: not only does the number of reported tests not match how many are in my suite, but it doesn’t even match how many are shown in the Travis log!

Do you see anything like that?

**Comment by mattyohe** [comment]
On spot checking, it seems the counts are matching up...

**Comment by pcantrell** [comment]
Hmm, well, thanks for checking.

As an experiment, I added a "sleep 20" at the end of my travis script and haven't seen any failed builds yet since doing that. Any luck with that?

**Comment by mattyohe** [comment]
@pcantrell huh, no I did have a `sleep 3` line in my travis.yml scripts key. The reason for that was to address issues with logs getting cut off. #4716

**Comment by mattyohe** [comment]
Continuing to see this issue on builds.

**Comment by pcantrell** [comment]
I traced my inaccurate spec counts to a race condition in Nocilla (an HTTP stub library which turns out to be wildly thread-unsafe).

I haven't seen the “peer channel” message since adding the sleep at the end of my script — but that’s hardly a confirmation that the bug is fixed, especially since the project in question has been relatively quiet for a couple weeks. I’ll post again here if I see more problems.

**Comment by solarce** [comment]
I apologize for the delay in an update to this issue, it is definitely a frustrating issue. We're still digging into why we're seeing this happen, it seems to be a bug in our worker, https://github.com/travis-ci/worker, which manages creating build VMs and running the build over SSH, where it's terminating the SSH session before the log buffer is fully flushed. 

This is why the `sleep N` trick works, as it gives the build enough running time for the logs to finish publishing. We are actively working on getting this squashed as well as getting updated to Xcode 7 and 7.1 beta out, so we appreciate your patience while we work through this issue.

Please feel free to reach out to support@travis-ci.com if you need further help for now.

**Comment by esetnik** [comment]
I'm still having the exact same issue. Will try the sleep trick and report back.

**Comment by esetnik** [comment]
The sleep trick worked but i'm not sure why. I contacted travis support but they were not helpful regarding the issue.

**Comment by onevcat** [comment]
The same issue for me. ([this build](https://travis-ci.org/onevcat/Kingfisher/jobs/152983858)). I will try the sleep trick too.

**Comment by JustinJiaDev** [comment]
Same issue for me as well (https://travis-ci.org/TintPoint/Overlay/jobs/154072294).

Xcode 8 beta 6 / iOS 10.0

**Comment by broadwaylamb** [comment]
+1

**Comment by chrisballinger** [comment]
We are also having this problem: https://travis-ci.org/ChatSecure/XMPPFramework/builds/164165106#L3002

> The command "xcodebuild -workspace Xcode/Testing-iOS/XMPPFrameworkTests.xcworkspace -scheme XMPPFrameworkTests -sdk iphonesimulator -destination 'name=iPhone 6' test" exited with 65.

Works fine from the command line, and more curiously, worked without issue a few days ago.

**Comment by samjarman** [comment]
+1

**Comment by cepages** [comment]
+1

**Comment by ohadschn** [comment]
Also reported on Open Radar: http://www.openradar.me/29785686

**Comment by pluie-cloud** [comment]
@pcantrell i face the same problem.The problem has been solved when i restart my iphone.hole that would be useful for you
