### ISSUE TITLE
Rackspace deploy broken on Linux

### ISSUE THREAD

**Issue by matthew-brett** [travis-ci/travis-ci#4853]
Upload to Rackspace from Linux VMs appears to be broken.

This seems to have happened in the last few hours.

https://travis-ci.org/matthew-brett/travis-wheel-builder/jobs/82243064

```
Fetching: net-ssh-3.0.1.gem (100%)
ERROR:  Error installing fog:
    net-ssh requires Ruby version >= 2.0.
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- fog (LoadError)
    from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.4/lib/dpl/provider.rb:74:in `requires'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.4/lib/dpl/provider/cloud_files.rb:6:in `<class:CloudFiles>'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.4/lib/dpl/provider/cloud_files.rb:5:in `<class:Provider>'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.4/lib/dpl/provider/cloud_files.rb:4:in `<module:DPL>'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.4/lib/dpl/provider/cloud_files.rb:3:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.4/lib/dpl/provider.rb:56:in `const_get'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.4/lib/dpl/provider.rb:56:in `block in new'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.4/lib/dpl/cli.rb:41:in `fold'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.4/lib/dpl/provider.rb:53:in `new'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.4/lib/dpl/cli.rb:31:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.4/lib/dpl/cli.rb:7:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.4/bin/dpl:5:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by matthew-brett** [comment]
This appears to be the same problem as earlier appeared on the OSX machines:

https://github.com/travis-ci/travis-ci/issues/4635

The workaround given in that issue also works here.

**Comment by BanzaiMan** [comment]
OK. I've pushed a fix to the `bug-rackspace` branch. Could you test it with:

```yaml
deploy:
  provider: clould_files
  edge:
    branch: bug-rackspace # <= new!
  ⋮ # rest
```

Thanks!

**Comment by matthew-brett** [comment]
Thanks for this.   I tried this here : https://travis-ci.org/matthew-brett/travis-wheel-builder/jobs/82765438 - but get this message:

```
Skipping a deployment with the cloudfiles provider because this branch is not permitted
```

Is travis getting confused between my repo branch and the deploy code branch?

https://github.com/matthew-brett/travis-wheel-builder/blob/5066057f134eb1b064d089393a95e9164f56a6ed/.travis.yml

Thanks a lot

**Comment by BanzaiMan** [comment]
@matthew-brett Yes, it is. It's a bug I've yet to work on fixing. Could you add:

```yaml
⋮
  on:
    all_branches: true
```
under `deploy`? Thanks.

**Comment by matthew-brett** [comment]
Seem to be getting the error still:

https://travis-ci.org/matthew-brett/travis-wheel-builder/jobs/82795231

```
Switched to a new branch 'bug-rackspace'
0.56sWARNING:  pessimistic dependency on rspec (~> 3.0.0, development) may be overly strict
  if rspec is semantically versioned, use:
    add_development_dependency 'rspec', '~> 3.0', '>= 3.0.0'
WARNING:  open-ended dependency on rspec-its (>= 0, development) is not recommended
  if rspec-its is semantically versioned, use:
    add_development_dependency 'rspec-its', '~> 0'
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
WARNING:  open-ended dependency on simplecov (>= 0, development) is not recommended
  if simplecov is semantically versioned, use:
    add_development_dependency 'simplecov', '~> 0'
WARNING:  open-ended dependency on coveralls (>= 0, development) is not recommended
  if coveralls is semantically versioned, use:
    add_development_dependency 'coveralls', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: dpl
  Version: 1.8.5.travis.94.1
  File: dpl-1.8.5.travis.94.1.gem
0.01s0.01s~/build/matthew-brett/travis-wheel-builder/wheelhouse
0.01s0.64sERROR:  Could not find a valid gem 'dpl-*.gem' (>= 0) in any repository
The command "rvm 1.9.3 --fuzzy do ruby -S gem install dpl-*.gem --local --pre" failed and exited with 2 during .
```

**Comment by BanzaiMan** [comment]
Ah, you `cd` in `before_deploy`. This is a problem with the `edge.branch`. I've known about this issue, but haven't fixed it. :-S

**Comment by BanzaiMan** [comment]
Since it's not working right now, there is little to lose by releasing my fix. It is available in v1.8.5. Please test it, and close this issue if it's fixed.

**Comment by matthew-brett** [comment]
I'm afraid it is still not working for me:

```
Fetching: dpl-1.8.5.gem (100%)
Successfully installed dpl-1.8.5
1 gem installed
dpl.1
Installing deploy dependencies
Fetching: net-ssh-2.9.2.gem (100%)
Successfully installed net-ssh-2.9.2
1 gem installed
Fetching: mini_portile-0.6.2.gem (100%)
Successfully installed mini_portile-0.6.2
Fetching: nokogiri-1.6.6.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.6.2
Fetching: net-scp-1.2.1.gem (100%)
Successfully installed net-scp-1.2.1
Fetching: mime-types-2.6.2.gem (100%)
Successfully installed mime-types-2.6.2
Fetching: formatador-0.2.5.gem (100%)
Successfully installed formatador-0.2.5
Fetching: excon-0.45.4.gem (100%)
Successfully installed excon-0.45.4
Fetching: builder-3.2.2.gem (100%)
Successfully installed builder-3.2.2
Fetching: fog-core-1.32.1.gem (100%)
Successfully installed fog-core-1.32.1
Fetching: fog-xml-0.1.2.gem (100%)
Successfully installed fog-xml-0.1.2
Fetching: fog-voxel-0.1.0.gem (100%)
Successfully installed fog-voxel-0.1.0
Fetching: CFPropertyList-2.3.1.gem (100%)
Successfully installed CFPropertyList-2.3.1
Fetching: fission-0.5.0.gem (100%)
Successfully installed fission-0.5.0
Fetching: fog-vmfusion-0.1.0.gem (100%)
Successfully installed fog-vmfusion-0.1.0
Fetching: fog-terremark-0.1.0.gem (100%)
Successfully installed fog-terremark-0.1.0
Fetching: multi_json-1.11.2.gem (100%)
Successfully installed multi_json-1.11.2
Fetching: fog-json-1.0.2.gem (100%)
Successfully installed fog-json-1.0.2
Fetching: fog-storm_on_demand-0.1.1.gem (100%)
Successfully installed fog-storm_on_demand-0.1.1
Fetching: fog-softlayer-0.4.7.gem (100%)
Successfully installed fog-softlayer-0.4.7
Fetching: fog-serverlove-0.1.2.gem (100%)
Successfully installed fog-serverlove-0.1.2
Fetching: fog-sakuracloud-1.3.3.gem (100%)
Successfully installed fog-sakuracloud-1.3.3
Fetching: fog-riakcs-0.1.0.gem (100%)
Successfully installed fog-riakcs-0.1.0
Fetching: fog-radosgw-0.0.4.gem (100%)
Successfully installed fog-radosgw-0.0.4
Fetching: fog-profitbricks-0.0.5.gem (100%)
Successfully installed fog-profitbricks-0.0.5
Fetching: fog-powerdns-0.1.1.gem (100%)
Successfully installed fog-powerdns-0.1.1
Fetching: fog-local-0.2.1.gem (100%)
Successfully installed fog-local-0.2.1
Fetching: fog-google-0.1.1.gem (100%)
ERROR:  Error installing fog:
	fog-google requires Ruby version >= 2.0.
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- fog (LoadError)
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.5/lib/dpl/provider.rb:74:in `requires'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.5/lib/dpl/provider/cloud_files.rb:7:in `<class:CloudFiles>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.5/lib/dpl/provider/cloud_files.rb:5:in `<class:Provider>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.5/lib/dpl/provider/cloud_files.rb:4:in `<module:DPL>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.5/lib/dpl/provider/cloud_files.rb:3:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.5/lib/dpl/provider.rb:56:in `const_get'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.5/lib/dpl/provider.rb:56:in `block in new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.5/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.5/lib/dpl/provider.rb:53:in `new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.5/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.5/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.5/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
```

https://travis-ci.org/matthew-brett/travis-wheel-builder/jobs/82994189

**Comment by BanzaiMan** [comment]
ugh. now `fog` is. :-/

**Comment by BanzaiMan** [comment]
OK, 1.8.6 is out with the latest round of fixes. Please test it.

**Comment by matthew-brett** [comment]
Success on Linux : https://travis-ci.org/matthew-brett/travis-wheel-builder

and OSX : https://travis-ci.org/MacPython/numexpr-wheels

Thanks for doing that.

**Comment by matthew-brett** [comment]
Has this problem returned?

https://travis-ci.org/MacPython/nipy-wheels/jobs/86487255

```
Fetching: fog-ecloud-0.3.0.gem (100%)
Successfully installed fog-ecloud-0.3.0
Fetching: fog-google-0.1.1.gem (100%)
ERROR:  Error installing fog:
	fog-google requires Ruby version >= 2.0.
/Users/travis/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- fog (LoadError)
```

**Comment by BanzaiMan** [comment]
Looks like `fog` 1.35.0 is now requiring `fog-google` 0.1.1 and up.

**Comment by BanzaiMan** [comment]
1.8.7 is out with the fix.

**Comment by matthew-brett** [comment]
Great - thanks for your quick response.

**Comment by holandes22** [comment]
Hi, 

I'm getting a similar error for package mime-types-data since last night, when trying to deploy to Rackspace cloudfiles.

```
Installing deploy dependencies
Fetching: net-ssh-2.9.2.gem (100%)
Successfully installed net-ssh-2.9.2
1 gem installed
Fetching: mime-types-data-3.2015.1120.gem (100%)
ERROR:  Error installing fog-google:
	mime-types-data requires Ruby version >= 2.0.
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- fog/google (LoadError)
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider.rb:76:in `requires'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider/cloud_files.rb:7:in `<class:CloudFiles>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider/cloud_files.rb:5:in `<class:Provider>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider/cloud_files.rb:4:in `<module:DPL>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider/cloud_files.rb:3:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider.rb:58:in `const_get'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider.rb:58:in `block in new'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/cli.rb:41:in `fold'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider.rb:55:in `new'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/cli.rb:31:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/cli.rb:7:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/bin/dpl:5:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

Seems related right?

**Comment by oryband** [comment]
this problem happens now to me when deploying to aws s3:
```
Installing deploy dependencies
Fetching: jmespath-1.1.3.gem (100%)
Successfully installed jmespath-1.1.3
Fetching: aws-sdk-core-2.2.1.gem (100%)
Successfully installed aws-sdk-core-2.2.1
Fetching: aws-sdk-resources-2.2.1.gem (100%)
Successfully installed aws-sdk-resources-2.2.1
Fetching: aws-sdk-2.2.1.gem (100%)
Successfully installed aws-sdk-2.2.1
4 gems installed
Fetching: mime-types-data-3.2015.1120.gem (100%)
ERROR:  Error installing mime-types:
	mime-types-data requires Ruby version >= 2.0.
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- mime-types (LoadError)
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider.rb:76:in `requires'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider/s3.rb:7:in `<class:S3>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider/s3.rb:5:in `<class:Provider>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider/s3.rb:4:in `<module:DPL>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider/s3.rb:3:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider.rb:58:in `const_get'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider.rb:58:in `block in new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/provider.rb:55:in `new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.8/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by oryband** [comment]
@fuzzyami @doodyparizada @avivl @liorama @gadisr

**Comment by oryband** [comment]
maybe related to #5145

**Comment by antonym** [comment]
This recently broke again, the workaround in #5145 works but the solution for that issue did not appear to fix Cloud Files.

**Comment by BanzaiMan** [comment]
@antonym Please include a build log URL that shows your problem.

**Comment by antonym** [comment]
@BanzaiMan https://travis-ci.org/antonym/netboot.xyz/builds/92757924

**Comment by ariddell** [comment]
This is happening to me. I tried the fix mentioned in #5145 and it did not work.
@BanzaiMan https://travis-ci.org/ariddell/lda-wheel-builder/jobs/112682021

**Comment by BanzaiMan** [comment]
@ariddell That build is on the `feature/update-terryfy` branch, so the deployment doesn't happen. https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A

**Comment by BanzaiMan** [comment]
@antonym Sorry for the delay, that build had some dependency issue which should have been resolved by now. Is it still failing for you?

**Comment by matthew-brett** [comment]
Sorry to resurrect this old thread - but should I expect this deploy method to work on trusty containers?  It appears not to: https://travis-ci.org/MacPython/astropy-wheels/jobs/137378811

**Comment by BanzaiMan** [comment]
@matthew-brett Where do you see the deployment error there?

**Comment by matthew-brett** [comment]
Sorry - there is no error recorded in the log, but the deploy step does not trigger, and the build is red on the travis interface despite there being no failed commands.   The same deploy configuration on a precise container works fine : https://travis-ci.org/MacPython/astropy-wheels/jobs/136980570

**Comment by BanzaiMan** [comment]
The problem with https://travis-ci.org/MacPython/astropy-wheels/jobs/137378811 is that it is using https://github.com/matthew-brett/multibuild/tree/cd78459049429cc65015c20356e13c033a20a1d3, which sets [`errexit`](https://github.com/matthew-brett/multibuild/blob/cd78459049429cc65015c20356e13c033a20a1d3/travis_osx_steps.sh#L3), which causes the first nonzero command exit to cause the entire build to halt.

It is not clear what command is failing, but something is. In order to troubleshoot this further, the option has to be unset.

**Comment by Gopikrishna19** [comment]
same issue: https://travis-ci.org/my-librarian/server-core/builds/150259142

**Comment by Gopikrishna19** [comment]
Tried to manually install Ruby@2.1.1 but still failed: https://travis-ci.org/my-librarian/server-core/builds/150260062

**Comment by BanzaiMan** [comment]
@Gopikrishna19 Yours is a failure with OpenShift deployment provider. It's fixed on the pre-release version.

```yaml
deploy:
  provider: openshift
  edge: true
```

**Comment by Gopikrishna19** [comment]
@BanzaiMan Thanks, it worked :)
