### ISSUE TITLE
Cannot acces caches informations

### ISSUE THREAD

**Issue by j0k3r** [travis-ci/travis-ci#5855]
Let says I want to access caches information for a repo.

- I'm going to a build on Travis: https://travis-ci.org/wallabag/wallabag/builds/120611087
- Under "More options", I hit "Caches"

And then a message appear :
> There was an error while loading data.

Here are the console information:

```
vendor-58fc5d1….js:19 Attempting transition to caches
vendor-58fc5d1….js:13 Preparing to transition from 'main.repo.error' to 'main.repo.caches'
vendor-58fc5d1….js:19 Transition #8: caches: calling beforeModel hook
vendor-58fc5d1….js:19 Transition #8: caches: calling deserialize hook
vendor-58fc5d1….js:19 Attempting transition to repo.loading
vendor-58fc5d1….js:13 Intermediate-transitioned into 'main.repo.loading'
api.travis-ci.org/repos/1003619/caches:1 GET https://api.travis-ci.org/repos/1003619/caches 
120611087:1 XMLHttpRequest cannot load https://api.travis-ci.org/repos/1003619/caches. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://travis-ci.org' is therefore not allowed access. The response had HTTP status code 500.
travis-7d165ca….js:5 [ERROR] API responded with an error (0): ""
vendor-58fc5d1….js:19 Attempting transition to repo.error
vendor-58fc5d1….js:13 Intermediate-transitioned into 'main.repo.error'
vendor-58fc5d1….js:12 Error while processing route: cachesw @ vendor-58fc5d1….js:12F.error @ vendor-58fc5d1….js:13E @ vendor-58fc5d1….js:12u @ vendor-58fc5d1….js:19i.trigger @ vendor-58fc5d1….js:19(anonymous function) @ vendor-58fc5d1….js:19y @ vendor-58fc5d1….js:19b @ vendor-58fc5d1….js:19v @ vendor-58fc5d1….js:19f @ vendor-58fc5d1….js:19(anonymous function) @ vendor-58fc5d1….js:14r.invoke @ vendor-58fc5d1….js:6r.flush @ vendor-58fc5d1….js:6n.flush @ vendor-58fc5d1….js:6o.end @ vendor-58fc5d1….js:6(anonymous function) @ vendor-58fc5d1….js:6
vendor-58fc5d1….js:19 Transition #8: caches: transition was aborted
vendor-58fc5d1….js:14 undefined
```

It seems that `https://api.travis-ci.org/repos/1003619/caches` returns an error 500.

BTW, the problem doesn't appear on travis-ci.com.

Tested on Chrome (Version 49.0.2623.110 (64-bit)) on Ubuntu 15.10.

**Comment by teppeis** [comment]
Same problem.

Also here is output of travis CLI:

```console
$ travis cache --debug
** Loading "/Users/teppeis/.travis/config.yml"
** Timeout::Error: execution expired
** Loading gh
** GET "config"
**   took 0.26 seconds
** GitHub API: HEAD /repos/teppeis/grunt-fixclosure
**   took 1.3 seconds
** GET "repos/teppeis/grunt-fixclosure"
**   took 0.22 seconds
** GET "users/"
**   took 0.23 seconds
** GET "users/permissions"
**   took 0.32 seconds
** GET "repos/1543477/caches" {}
**   took 0.24 seconds
server error (500: "{\"error\":\"Travis encountered an error, sorry :(\"}")
```

**Comment by BanzaiMan** [comment]
Sorry about the issue. I believe it's been fixed. Could you confirm?

**Comment by j0k3r** [comment]
I do not have the _caches_ options under _More options_ any more. Can't confirm it's fixed :confused: 

<img width="182" alt="capture d ecran 2016-04-05 a 22 35 06" src="https://cloud.githubusercontent.com/assets/62333/14297383/bd991bcc-fb7e-11e5-9685-8e4f808f883b.PNG">

**Comment by BanzaiMan** [comment]
@j0k3r That is very curious. I see that you have admin access to wallabag/wallabag, so you should see it. Could you try logging out and back in? Do you have any other repository to which you have push access and that has caches?

**Comment by nicosomb** [comment]
After logout, same problem than @j0k3r.
On other projects (nicosomb/cdetc.fr or Smile-SA/elasticsuite), I have the Caches button).

**Comment by MariadeAnton** [comment]
Hey, I did run into this myself and triggering a sync + refreshing the page fixed the issue. Could you try this out and let us know how it goes? Thank you!

**Comment by j0k3r** [comment]
@MariadeAnton you mean "sync account" in my profile page? Just did that and also did the sync on the organization profile. After refreshing, still no other options than Request.

BUT after switching from a project to an other and coming back to wallabag/wallabag, the Caches and Settings options are back.

And if I open a new tab to travis, these options are gone _again_ ... :flushed:

**Comment by MariadeAnton** [comment]
@j0k3r Thanks for trying it out! We've been able to reproduce and are currently investigating.

**Comment by MariadeAnton** [comment]
We've deployed a fix for this and it should be working properly now. Can y'all confirm?

**Comment by j0k3r** [comment]
Looks good to me !

**Comment by MariadeAnton** [comment]
Closing this issue as it seems to be fixed, otherwise, please comment below.

**Comment by leofernandezg** [comment]
I think that this issue is back in travis-ci.com :

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/23743636/114589295-ebfc3c80-9c5d-11eb-9714-9b2b2745a848.png">

**Comment by charliegeiger89** [comment]
Same issue on travis-ci.com, seeing 500 in the console.
