### ISSUE TITLE
Waiting for status to be reported

### ISSUE THREAD

**Issue by DaikiMaekawa** [travis-ci/travis-ci#5856]
the status doesn't switch from "Waiting for status to be reported" even though any job isn't running like the following issue.

https://github.com/travis-ci/travis-ci/issues/5542

**Comment by DaikiMaekawa** [comment]
It has happened on this issue. https://github.com/DaikiMaekawa/daiki-env-setup/pull/47
Is there anyone who have any idea?

**Comment by BanzaiMan** [comment]
@DaikiMaekawa Did you rename this repository? Data sync was a bit confused. I triggered the sync (you can also do this at https://travis-ci.org/DaikiMaekawa/profile) and I now see the corresponding build https://travis-ci.org/DaikiMaekawa/daiki-env-setup/builds/120671896. Unfortunately, the GitHub status update did not happen, so I suggest pushing another commit to it.

**Comment by DaikiMaekawa** [comment]
Yeah. I changed my repository name before.
So, I pushed a dummy commit and then travis came to work.

Thanks a lot!

**Comment by bblacey** [comment]
We're seeing the same issue on FreeCAD.  You can see in the [pull requests](https://github.com/FreeCAD/FreeCAD/pulls) that the first succeeded, two are still waiting for status and the last completed.  There were no changes to the repository or settings during between the first and last other than pull requests being created on GitHub but no corresponding Travis-CI jobs were created for the two PRs pending status.

**Comment by SkyzohKey** [comment]
I have the same issue today here:
https://github.com/RicinApp/Ricin/pull/109 :/

**Comment by benjaoming** [comment]
Seeing the same issue consequently, so we cannot use `[ci skip]`... the commit is getting ignored all fine, it doesn't show up on Travis... but the status hangs forever.

https://github.com/learningequality/kolibri/pull/2985

![image](https://user-images.githubusercontent.com/374612/34183483-4e8f3e18-e51b-11e7-9df1-ed445d992c67.png)

**Comment by jaques-sam** [comment]
We also have the issue still:
![image](https://user-images.githubusercontent.com/42445148/45495589-d5269e00-b773-11e8-9ef3-a6e118b0e9c8.png)

**Comment by BanzaiMan** [comment]
Please subscribe to https://www.traviscistatus.com/incidents/d16clc6zpd85.

**Comment by Drafter500** [comment]
I have the same issue, has anyone had a chance to overcome this?

**Comment by jaques-sam** [comment]
This happens sporadically, but it every time it goes green after several minutes/hours... You need to have patience :-)

**Comment by donut87** [comment]
https://github.com/saros-project/saros/pull/249#pullrequestreview-161549307
This is hanging for 2 days now. I do not want to create a dummy commit. Is there any other solution?

**Comment by benjaoming** [comment]
@donut87 - AFAIK: `git commit --amend`, then `git push --force`.

**Comment by donut87** [comment]
@benjaoming I would categorize this as invisible dummy commit. Thanks for the idea. It is not exactly what I was looking for, but at least I do not have to do `git commit --allow-empty -m "trigger travis"`

**Comment by mjenny** [comment]
I am seeing this issue as well:
![image](https://user-images.githubusercontent.com/4191545/46605227-169f3480-caf9-11e8-90bc-27b08797bb99.png)

**Comment by andrmoel** [comment]
Can agree. Our travis check doesn't run too on github since 2 days.

There are no incidents on https://www.traviscistatus.com/

**Comment by andrmoel** [comment]
The solution is descibed here: https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories

**Comment by benjaoming** [comment]
Thanks for referring to the solution @andrmoel 

Travis team: Deprecating and removing something that Just Works (tm) for others feels a bit like well.. disruption for the sake of disruption? :) It would be nice with at least a bit of motivation.. like "we are making this change so that we can improve x".

**Comment by benjaoming** [comment]
To answer my own question: Maybe Travis is doing us a favor so that people will have a solution ready when Github pulls the plug. It's Github that should have considered keeping the old Status API.

![image](https://user-images.githubusercontent.com/374612/46668679-72d38880-cbcd-11e8-9fe6-427ac14fc0f3.png)

**Comment by BanzaiMan** [comment]
See #10204 for the most recent issue manifesting in this.
