### ISSUE TITLE
Android - Missing emulator ABI due to bad SDK Tools version

### ISSUE THREAD

**Issue by barbeau** [travis-ci/travis-ci#6122]
It looks like there was a bad version of the Android SDK tools that got pushed out that was missing the ABIs for the Google API 23 emulator.

I have a branch [here](https://github.com/barbeau/android-maps-utils/commits/fixTravis) that should work, but it's failing:
https://travis-ci.org/barbeau/android-maps-utils/builds/134484281

Android SDK Tools `24.0.2` is what Travis is using, and doing `android list targets` on Travis shows:

~~~
id: 10 or "Google Inc.:Google APIs:23"
     Name: Google APIs
     Type: Add-On
     Vendor: Google Inc.
     Revision: 1
     Description: Android + Google APIs
     Based on Android 6.0 (API level 23)
     Libraries:
      * com.google.android.media.effects (effects.jar)
          Collection of video effects
      * com.android.future.usb.accessory (usb.jar)
          API for USB Accessories
      * com.google.android.maps (maps.jar)
          API for Google Maps
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
~~~

`android list targets` on my machine with Android SDK Tools `25.1.7` correctly shows the ABIs:

~~~
id: 27 or "Google Inc.:Google APIs:23"
     Name: Google APIs
     Type: Add-On
     Vendor: Google Inc.
     Revision: 1
     Description: Android + Google APIs
     Based on Android 6.0 (API level 23)
     Libraries:
      * com.android.future.usb.accessory (usb.jar)
          API for USB Accessories
      * com.google.android.media.effects (effects.jar)
          Collection of video effects
      * com.google.android.maps (maps.jar)
          API for Google Maps
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, W
XGA720, WXGA800, WXGA800-7in
 Tag/ABIs : google_apis/armeabi-v7a, google_apis/x86, google_apis/x86_64
~~~

Could we get an updated Android Travis image to fix this and make the ABIs available for Google API Level 23?

See also https://github.com/googlemaps/android-maps-utils/pull/283#issuecomment-223044065 and https://github.com/googlemaps/android-maps-utils/issues/284.

**Comment by BanzaiMan** [comment]
Looks like a duplicate of https://github.com/travis-ci/travis-ci/issues/5648.

**Comment by barbeau** [comment]
@BanzaiMan I'm still seeing the same error for the bad Android emulator image when trying to build on Travis:
https://travis-ci.org/barbeau/android-maps-utils/builds/134497093

When will the Travis image be updated?

**Comment by BanzaiMan** [comment]
Where is this component defined? sys-img-armeabi-v7a-addon-google_apis-google-23

If it is in `repository-11.xml`, you might need this: https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943

**Comment by barbeau** [comment]
Hmmm, this (from https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943) doesn't work:

~~~
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
~~~

Another failed build:
https://travis-ci.org/barbeau/android-maps-utils/builds/142816134

It says:

~~~
Android SDK Tools Version
24.0.2
~~~

...and current version on my desktop is `25.1.7`.

I'm not sure about where that component is defined, I'll need to dig a bit more...

**Comment by barbeau** [comment]
@BanzaiMan So looking at https://dl-ssl.google.com/android/repository/repository-11.xml, `armeabi-v7a` doesn't appear anywhere in that file.

It looks like it does come from https://dl.google.com/android/repository/sys-img/google_apis/sys-img.xml:

><sdk:system-image>
<!--
Generated from bid:2872745, branch:git_mnc-emu-release
~~~
<sdk:api-level>23</sdk:api-level>
<sdk:description>Google APIs ARM EABI v7a System Image</sdk:description>
<sdk:revision>14</sdk:revision>
<sdk:archives>
<sdk:archive>
<!-- Built on: Mon May 16 18:26:28 2016. -->
<sdk:size>386182705</sdk:size>
<sdk:checksum type="sha1">3f99c141ed3488a37f1547ba4e0593e8aabbc5f8</sdk:checksum>
<sdk:url>sysimg_armeabi-v7a-23_r14.zip</sdk:url>
</sdk:archive>
</sdk:archives>
<sdk:uses-license ref="android-sdk-license"/>
<sdk:abi>armeabi-v7a</sdk:abi>
<sdk:tag-id>google_apis</sdk:tag-id>
<sdk:tag-display>Google APIs</sdk:tag-display>
</sdk:system-image>
~~~

Any idea how I can get this to install properly on Travis with the above ABI?

**Comment by BanzaiMan** [comment]
Interesting. How does one get that XML file with `android update sdk` calls?

**Comment by barbeau** [comment]
It's one of the XML files fetched during the update process, but I get an `Error: Ignoring unknown package filter` for the emulator image - see below:

~~~
F:\APIs\android>echo y | android update sdk --no-ui --filter sys-img-armeabi-v7a
-google_apis-23
Refresh Sources:
  Fetching https://dl.google.com/android/repository/addons_list-2.xml
  Validate XML
  Parse XML
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: https://dl.google.com/android/repository/repository-11.xml
  Validate XML: https://dl.google.com/android/repository/repository-11.xml
  Parse XML:    https://dl.google.com/android/repository/repository-11.xml
  Fetching URL: https://dl.google.com/android/repository/addon.xml
  Validate XML: https://dl.google.com/android/repository/addon.xml
  Parse XML:    https://dl.google.com/android/repository/addon.xml
  Fetching URL: https://dl.google.com/android/repository/glass/addon.xml
  Validate XML: https://dl.google.com/android/repository/glass/addon.xml
  Parse XML:    https://dl.google.com/android/repository/glass/addon.xml
  Fetching URL: https://dl.google.com/android/repository/extras/intel/addon.xml
  Validate XML: https://dl.google.com/android/repository/extras/intel/addon.xml
  Parse XML:    https://dl.google.com/android/repository/extras/intel/addon.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/android/sys-img
.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/android/sys-img
.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/android/sys-img
.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/android-wear/sy
s-img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/android-wear/sy
s-img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/android-wear/sy
s-img.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/android-tv/sys-
img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/android-tv/sys-
img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/android-tv/sys-
img.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/google_apis/sys
-img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/google_apis/sys
-img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/google_apis/sys
-img.xml
  Fetching URL: https://s3.amazonaws.com/android-sdk-manager/redist/addon.xml
  Validate XML: https://s3.amazonaws.com/android-sdk-manager/redist/addon.xml
  Parse XML:    https://s3.amazonaws.com/android-sdk-manager/redist/addon.xml
Error: Ignoring unknown package filter 'sys-img-armeabi-v7a-google_apis-23'
Warning: The package filter removed all packages. There is nothing to install.
         Please consider trying to update again without a package filter.
~~~

I'm not very familiar with the SDK update process, so I'm not sure if I'm doing something wrong, or if something changed on Google's end that broke this process.  They've changed component names [in the past](http://stackoverflow.com/a/28751112/937715), but trying the different names here doesn't seem to fix anything.

**Comment by barbeau** [comment]
I think the main issue here, though, is that the newer version of SDK Tools isn't showing up on Travis (see my original post).

**Comment by barbeau** [comment]
@BanzaiMan Any ideas on fixing this?  It's blocking the use of Travis by projects like [android-map-utils](https://github.com/googlemaps/android-maps-utils) - basically any project that wants to use Google APIs emulator to run tests, which is required if you use Google Play Services in your unit tests.

**Comment by BanzaiMan** [comment]
Sorry, I do not. You can try reproducing it with our Docker image (https://quay.io/repository/travisci/travis-android) or, if you would like, we can provide you with access to a debug VM. Please email support@travis-ci.com if you do.

**Comment by ardock** [comment]
@barbeau, i think I solved this months ago, something about renamed ABIs and an extra tools required, I don't remember now

Try this: https://github.com/ardock/android-maps-utils/commits/a4fa636d21a6dfb7470bee16d0ddec14e7d312ea/.travis.yml

```
language: android
jdk: oraclejdk7
# Use the Travis Container-Based Infrastructure
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  global:
    - ANDROID_API_LEVEL=23
    - EMULATOR_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=23.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    # For Google APIs
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - addon-google_apis-google-$EMULATOR_API_LEVEL
    # Google Play Services
    - extra-google-google_play_services
    # Support library
    - extra-android-support
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository
    # Specify at least one system image
    - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-google_apis-$EMULATOR_API_LEVEL

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator

script:
  - ./gradlew clean check connectedCheck -x library:signArchives -PdisablePreDex
```

**Comment by barbeau** [comment]
Whoah, @ardock, [that works](https://travis-ci.org/barbeau/android-maps-utils/builds/151541898)!!!  Thank you so much, this has been driving me crazy :) :).  I'll close out this issue then.

**Comment by tir38** [comment]
@ardock why do you specify `ANDROID_API_LEVEL=23` ? Is this the `targetSdkVersion` and `compileSdkVersion` of the app? 

If so why do you need to specify `sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL` ? You don't use this system image.

**Comment by ardock** [comment]
@tir38 Yes, it's the [android platform](https://developer.android.com/studio/releases/platforms.html).

And yes, it's currently useless, but this is not my travis configuration, I only used it to try to fix that.

And they are probably waiting for api-23 + ci fixed to use it.

**Comment by tir38** [comment]
@ardock Do I need to specify the android sdk for the emulator? Or can Travis create an emulator w/out it. I.e. do I *need* `android-$EMULATOR_API_LEVEL` ?

**Comment by barbeau** [comment]
You need to specify the level for the emulator - IIRC at some point I split out `android-$EMULATOR_API_LEVEL` from the other `$ANDROID_API_LEVEL` because the API Level 23 emulators were buggy.  That allowed us to build with the latest API Level SDK but use the older emulator that still worked.

**Comment by tir38** [comment]
Ahh right! I see that when I run `android list sdk --no-ui --all --extended` it explicitly says I need the corresponding SDK:

```
id: 89 or "sys-img-armeabi-v7a-android-21"
     Type: SystemImage
     Desc: ARM EABI v7a System Image
           Revision 3
           Requires SDK Platform Android API 21
```


Also, I don't think this is correct if you are trying to start an emulator with Google APIs:

```
echo no | android create avd --force -n test -t "android-21" --abi armeabi-v7a --tag google_apis```

I think you are specifying the api level and tag incorrectly. I had to do this:

```
echo no | android create avd --force -n test -t "Google Inc.:Google APIs:21" --abi google_apis/armeabi-v7a
```

**Comment by barbeau** [comment]
The format has changed a few times with the API levels and SDK versions.   I know this currently works:
https://github.com/googlemaps/android-maps-utils/blob/master/.travis.yml

See http://stackoverflow.com/a/28751112/937715. 

See also for Android 7.0:
http://stackoverflow.com/questions/38415895/how-to-create-avd-with-android-7-0-with-google-apis/39253525#39253525

**Comment by tir38** [comment]
@barbeau took your suggestions and now Travis is hanging when trying to create hardware profile:

```
$ android list targets
$ android list sdk --no-ui --all --extended | grep -E '^id:' | awk -F '"' '{$1=""; print $2}'
$ android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
Android 5.0.1 is a basic Android platform.
Do you wish to create a custom hardware profile [no]
```

**Comment by ardock** [comment]
@tir38 This is probably because you are not using the same SDK tools that @barbeau and as he said it changed a few times. If you are using Travis-ci, the version is fixed :) if you use the same sequence:

```
android:
  components:
    - tools
    - platform-tools
    - tools
```

**Comment by barbeau** [comment]
@ardock Have you been able to get a Travis build working using API Level 24 or 25 emulators?

I'm seeing the same missing ABI problem (unless I'm missing something):
https://github.com/OneBusAway/onebusaway-android/issues/720#issuecomment-263402921

**Comment by yvolk** [comment]
I fixed my Travis builds, using above comments. Current version of the config file is here: https://github.com/andstatus/andstatus/blob/master/.travis.yml

In addition, I solved a problem with Android ADB doesn't propagate error code back to Travis CI by this simple method:
1. During adb testing I create a log file.
2. After test completion I search the file for "INSTRUMENTATION_STATUS: stack=" - its presence means that some failure occurred.

```
  - |
    adb shell am instrument -w -r -e annotation org.andstatus.app.context.Travis org.andstatus.app.tests/android.test.InstrumentationTestRunner |& tee build/adb-test.log
    retval=$?
    if [ $retval -ne 0 ]; then
      echo "error in adb, exit code: "$retval
      exit $retval
    fi

  # adb doesn't propagate exit code from tests, see https://code.google.com/p/android/issues/detail?id=3254
  # So we need to parse saved terminal log
  - |
    cat build/adb-test.log | grep "INSTRUMENTATION_STATUS: stack="
    if [ $? -eq 0 ]; then
      echo "Test failure found"
      exit 1
    else
      cat build/adb-test.log | grep "Test results for InstrumentationTestRunner"
    fi
```

**Comment by TedaLIEz** [comment]
I tried many solutions but came to the same issue, current config file: [https://github.com/TedaLIEz/ParsingPlayer/blob/dev/.travis.yml](https://github.com/TedaLIEz/ParsingPlayer/blob/dev/.travis.yml)
```
env:
  matrix:
    - TEST=unit
    - TEST=android ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - TEST=android ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
    - TEST=android ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
    - TEST=android ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
    - TEST=android ANDROID_TARGET=android-24 ANDROID_ABI=armeabi-v7a
    - TEST=android ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=10
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"


sudo: required

android:
  components:
    - tools
    - platform-tools
    - tools
    # looking for update
    - build-tools-25.0.2
    - build-tools-24.0.1
    - build-tools-23.0.2
    - android-22
    - android-23
    - android-24
    - android-25
    - extra-android-m2repository
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-23
    - sys-img-armeabi-v7a-android-24
    - sys-img-armeabi-v7a-android-25


licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'


```

It seems that android-23 and android-25 fail to find the filter package: [https://travis-ci.org/TedaLIEz/ParsingPlayer/jobs/206045334](https://travis-ci.org/TedaLIEz/ParsingPlayer/jobs/206045334)
```
$ android list targets
Available Android targets:

id: 1 or "android-10"
     Name: Android 2.3.3
     Type: Platform
     API level: 10
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WVGA800 (default), WVGA854
 Tag/ABIs : default/armeabi

id: 2 or "android-15"
     Name: Android 4.0.3
     Type: Platform
     API level: 15
     Revision: 5
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800
 Tag/ABIs : default/armeabi-v7a

id: 3 or "android-16"
     Name: Android 4.1.2
     Type: Platform
     API level: 16
     Revision: 5
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : default/armeabi-v7a

id: 4 or "android-17"
     Name: Android 4.2.2
     Type: Platform
     API level: 17
     Revision: 3
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : default/armeabi-v7a

id: 5 or "android-18"
     Name: Android 4.3.1
     Type: Platform
     API level: 18
     Revision: 3
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : default/armeabi-v7a

id: 6 or "android-19"
     Name: Android 4.4.2
     Type: Platform
     API level: 19
     Revision: 4
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : default/armeabi-v7a

id: 7 or "android-20"
     Name: Android 4.4W.2
     Type: Platform
     API level: 20
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.

id: 8 or "android-21"
     Name: Android 5.0.1
     Type: Platform
     API level: 21
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : default/armeabi-v7a

id: 9 or "android-22"
     Name: Android 5.1.1
     Type: Platform
     API level: 22
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : default/armeabi-v7a

id: 10 or "android-23"
     Name: Android 6.0
     Type: Platform
     API level: 23
     Revision: 3
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.

id: 11 or "android-24"
     Name: Android 7.0
     Type: Platform
     API level: 24
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : default/armeabi-v7a

id: 12 or "android-25"
     Name: Android 7.1.1
     Type: Platform
     API level: 25
     Revision: 3
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
```

**Comment by ardock** [comment]
@barbeau sorry i read you but I did't try it and I was so  busy at work, we use jenkins there.

My idea was to answer you with a solution another day...

Is @yvolk's solution also working in your case?, I'm interested on this topic but doubting between wait for a solution or try the hard path.

**Comment by barbeau** [comment]
@ardock Nope, still no luck on my end.  Will keep trying as time allows...

**Comment by albodelu** [comment]
@barbeau I posted a related sample in [stackoverflow](http://stackoverflow.com/a/42736695/1009132) and tested it in three projects.

The first sample, specially for your [Onebusaway](https://github.com/OneBusAway/onebusaway-android/issues/720) :
https://travis-ci.org/albodelu/android-maps-utils/builds/220859379
https://travis-ci.org/albodelu/Dexter/builds/220847349
https://travis-ci.org/albodelu/constraint-layout/builds/220841505

It's still a little tricky, I'll try to improve it and use QEMU-2.

**Comment by albodelu** [comment]
Related SO answer [here](https://stackoverflow.com/a/45177269/1009132).
