### ISSUE TITLE
R build failing on installing diagram package

### ISSUE THREAD

**Issue by oneillkza** [travis-ci/travis-ci#6244]
I just had a Travis build fail on a pull request while installing a dependency:

```
trying URL 'https://cloud.r-project.org/src/contrib/diagram_1.6.3.tar.gz'
Content type 'application/x-gzip' length 466691 bytes (455 KB)
==================================================
downloaded 455 KB

Installing diagram
Error in FUN(X[[i]], ...) : 
  Invalid comparison operator in dependency: >= 
Calls: <Anonymous> ... install -> install_deps -> dev_package_deps -> lapply -> FUN
Execution halted
```

This is peculiar, since my understanding (and reading of the current devtools code) is that >= should be a valid comparison operator for dependencies.

* [Failed build log here](https://api.travis-ci.org/jobs/141487546/log.txt?deansi=true)
* [a slightly older but working log here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/137692981/log.txt). 
* [The package in question](https://travis-ci.org/oneillkza/ContiBAIT ) 

@craigcitro @hadley @jimhester @rareaquaticbadger

**Comment by oneillkza** [comment]
I made a minimal example package which is also failing to install diagram, though with a different error:

https://github.com/oneillkza/travis_r_test

**Comment by oneillkza** [comment]
Is anyone interested in figuring this out? I just ran across another package for which the Travis-CI test is failing due to being unable to install diagram.

https://travis-ci.org/epurdom/clusterExperiment

It's slightly concerning that a large portion of R packages cannot be tested with Travis right now.

**Comment by jimhester** [comment]
This is caused by the bug fixed by https://github.com/hadley/devtools/pull/1257.

If you add `github_packages: devtools` to your travis.yml you will install the devel devtools (which now fixes this bug), which should allow you to install diagram.

**Comment by oneillkza** [comment]
Thanks! Giving that a try now.

**Comment by oneillkza** [comment]
Are you sure `github_packages` is a valid keyword for travis.yml? It doesn't seem to be installing the GitHub version of devtools, and defaulting to the CRAN version. I can't find any documentation for that keyword either.

I've also tried manually installing the latest devtools via wget and Rscript, but this still doesn't seem to work. The patch you describe is definitely in there, but it's either not working correctly, or getting overwritten by an older version of devtools. 

e.g: 
https://travis-ci.org/oneillkza/ContiBAIT/builds/145257997 -- using github_packages

https://travis-ci.org/oneillkza/ContiBAIT/builds/147326684 -- manually installing devtools via wget and Rscript.

**Comment by jimhester** [comment]
The key is r_github_packages, my mistake

**Comment by oneillkza** [comment]
Thanks -- trying that one.

Hmmm ... that gives me the following error:

```
Installing R packages from GitHub: devtools
0.75s$ Rscript -e 'devtools::install_github(c("devtools"), build_vignettes = FALSE)'
Error in username %||% getOption("github.user") %||% stop("Unknown username.") : 
  Unknown username.
Calls: <Anonymous> -> lapply -> FUN -> %||%
Execution halted
```

https://travis-ci.org/oneillkza/ContiBAIT/builds/147331963

**Comment by oneillkza** [comment]
Oh my mistake.

**Comment by oneillkza** [comment]
Also thanks, that seems to have done it!
