### ISSUE TITLE
shell_session_update error

### ISSUE THREAD

**Issue by afestein** [travis-ci/travis-ci#6307]
I am seeing a new error on an OSX / objective-c project which has previously been running fine: 

`/Users/travis/build.sh: line 109: shell_session_update: command not found`

It seems to be a new issue with the xcode7.3 OSX image, as it passes this stage if I revert back to the default by removing the `osx_image` line.

Contents of my travis.yml: 

```
language: objective-c
osx_image: xcode7.3
cache:
  bundler: true
  cocoapods: true
  directories:
    - build
before_install:
  - (ruby --version)
  - sudo chown -R travis ~/Library/RubyMotion
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion/build
  - sudo motion update
after_success:
  - bin/travis_deploy
script:
  - bundle install --jobs=3 --retry=3
  - pod repo update && rake pod:install
  - bundle exec rake clean
  - bundle exec rake spec
```

Link to the build: https://travis-ci.com/cvcnetwork/yesheis-motion-ios/builds/28293964

Any help greatly appreciated.

**Comment by BanzaiMan** [comment]
This appears to be an issue with RVM where it hooks to the `EXIT` signal. The message, while annoying, can safely be ignored.

**Comment by afestein** [comment]
Thanks for the reply. I'd be happy to ignore the error, but I think it's causing my build to fail. If I remove the `sudo motion update` in my `.travis.yml` the build passes fine. Would it be fair to say that this command "exited with 1" is causing the build to fail?

**Comment by afestein** [comment]
I figured this out. Yes it is because the RubyMotion update exits with a status code of 1 which technically I think should be a 0. I got around this by changing this line to `sudo motion update || echo 'up to date'` which lets the build keep going.

**Comment by abigailbunyan** [comment]
I'm having a different but related issue - my build succeeds fine, and the last thing I see is:

```
  The command "[build command]" exited with 0.
‣ store build cache
  Done. Your build exited with 0.
  /Users/travis/build.sh: line 109: shell_session_update: command not found
```

It looks like this has been fixed in RVM as of cbc4488028ccc682a872034ba823f61bf2d9cf6d - see
rvm/rvm#3627 for more details. It's not in `stable` at the moment so you need `rvm get head`.

**Comment by alphastryk** [comment]
I just started experiencing this error with both the xcode7.3 and the xcode8 images as of this morning. I will add `rvm get head` as a build step and see if that resolves my issue

**Comment by ssbarnea** [comment]
I can confirm that doing a `rvm get stable` is a workaround. 
See https://travis-ci.org/ssbarnea/InfraRed/jobs/185754445 which failed without one and the next build suceeds after adding upgrading rvm.

Now what I do not understand how it comes that Travis closed this bug because is clearly Travis bug that it contains a broken version of rvm.

**Comment by kousun12** [comment]
Any chance we can re-open this? Or if you guys on the travis team could update the ruby version to a stable build on the osx machines? could save a decent amount of time if we didn't have to fetch stable all the time

**Comment by igoriols** [comment]
Hey, guys!

Any update on this? I'm still getting this error.

**Comment by toblerpwn** [comment]
Also for me on `xcode8.2`

**Comment by jpsim** [comment]
Just another data point that this occurred for me on a `xcode8.3` image: https://travis-ci.org/realm/SwiftLint/jobs/254569424#L971

**Comment by PeterDaveHello** [comment]
Same here: https://travis-ci.org/leonsoft-kras/transmisson-remote-gui/jobs/255515897 on xcode8.3

**Comment by 0mp** [comment]
Same here: https://travis-ci.org/openbsm/openbsm/jobs/260658900

**Comment by Richard-Cao** [comment]
`rvm get stable` error: https://travis-ci.org/attentiveness/reading/jobs/267660960
image: xcode8.2

**Comment by Lecrapouille** [comment]
I'm not using Xcode but clang or g++ and l have the same issue, but in my case, in the middle of my unit test execution https://travis-ci.org/Lecrapouille/SimTaDyn/jobs/276062485

**Comment by Dekken** [comment]
I've been seeing this on Mac builds since the maintenance last weekend. any suggestions?

**Comment by Seluj78** [comment]
I've been seeing this for a few days now, can't tell for how long, Here's a link anyway to the job 
https://travis-ci.com/cbcercas/21-42sh/jobs/102242690

**Comment by Dekken** [comment]
@Seluj78 

I got this working but adding the following lines to .travis.yml

```
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get stable; fi
```

**Comment by tgsmith61591** [comment]
@Dekken I tried your fix and encountered yet more errors:

```bash
$ if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get stable; fi
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
Verifying /Users/travis/.rvm/archives/rvm-installer.asc
gpg: Signature made Sat Sep  9 19:49:18 2017 GMT
gpg:                using RSA key E206C29FBF04FF17
gpg: Can't check signature: No public key
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/Users/travis/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc'!
try downloading the signatures:

    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

/Users/travis/.rvm/scripts/functions/cli: line 243: return: _ret: numeric argument required


The command "if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get stable; fi" failed and exited with 255 during .
```

Full log here: https://travis-ci.org/tgsmith61591/pyramid/jobs/326047026

Anyone else encountering this issue?

**Comment by bsipocz** [comment]
Getting rvm stable is actually not enough (we were already using head), as the most recent issues are with checking the signatures, so one either needs 
```
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
```
 or   
```
command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
```

**Comment by maelvalais** [comment]
Hi,
Thank you for the trick @bsiggelkow! I still get a build failure though (only during the deploy step).

Before using `rvm get stable`, the log was: ([full log](https://travis-ci.org/touist/touist/jobs/326078830))

```
travis_time:end:03a10c90:start=1515355084898785000,finish=1515355088116799000,duration=3218014000
[0Ktravis_fold:end:before_deploy.1
[0Ktravis_fold:start:before_deploy.2
[0Ktravis_time:start:08c19280
[0K$ cd $TRAVIS_BUILD_DIR



travis_time:end:08c19280:start=1515355088135058000,finish=1515355088151503000,duration=16445000
[0Ktravis_fold:end:before_deploy.2
[0Ktravis_fold:start:dpl.0
[0K/Users/travis/.travis/job_stages: line 782: shell_session_update: command not found

travis_time:start:03939b0f
[0K/Users/travis/.rvm/scripts/functions/support: line 57: shell_session_update: command not found
```

After ([full log](https://travis-ci.org/touist/touist/jobs/326296101)):
```
travis_time:end:1a38d565:start=1515407466725436000,finish=1515407470354468000,duration=3629032000
[0Ktravis_fold:end:before_deploy.2
[0Ktravis_fold:start:before_deploy.3
[0Ktravis_time:start:20ad1717
[0K$ cd $TRAVIS_BUILD_DIR



travis_time:end:20ad1717:start=1515407470373414000,finish=1515407470391359000,duration=17945000
[0Ktravis_fold:end:before_deploy.3
[0Ktravis_fold:start:dpl.0
[0Ktravis_time:start:0077421c
[0K
```

For some reason the build fails anyway right after entering the deploy step 😞

**Comment by danbohea** [comment]
Had the same error on osx builds. Tried everything in this thread to no avail.

Turns out it was because Travis has stopped liking the use of `cp -n` on osx. It's fine without the `-n`, no idea why. Took an age to debug. Ended up replacing `cp` usage with `rsync` equivalents. E.g:

```sh
# Fails
cp -n src/file.yml dest/file.yml

# Works
rsync src/file.yml dest/file.yml --ignore-existing
```

- Broken: https://travis-ci.org/danbohea/macsible/jobs/338493011
- Fixed (well, no longer fails 2mins in):  https://travis-ci.org/danbohea/macsible/jobs/338683410

**Comment by tgsmith61591** [comment]
@danbohea Unfortunately this didn't work for me, it still breaks (seriously guys, this is getting crazy):

```bash
cp $TEST_DIR/.coverage $TRAVIS_BUILD_DIR
```

I'll try with `rsync` rather than `cp`.
