### ISSUE TITLE
PyPi deployment fails

### ISSUE THREAD

**Issue by e-kolpakov** [travis-ci/travis-ci#6891]
Looks like one of the PyPi deployment tools have a dependency problem

[Full log](https://travis-ci.org/edx/edx-enterprise/jobs/176668013)

Relevant log records:

```
... snip ...
running install_egg_info
Copying edx_enterprise.egg-info to build/bdist.linux-x86_64/wheel/edx_enterprise-0.3.0-py3.5.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/edx_enterprise-0.3.0.dist-info/WHEEL
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests_toolbelt/_compat.py", line 49, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests/packages/urllib3/contrib/appengine.py", line 45, in <module>
    from urlparse import urljoin
ImportError: No module named 'urlparse'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/bin/twine", line 7, in <module>
    from twine.__main__ import main
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/twine/__main__.py", line 20, in <module>
    from twine.cli import dispatch
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/twine/cli.py", line 23, in <module>
    import requests_toolbelt
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests_toolbelt/_compat.py", line 51, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: No module named 'urllib3'
```

**Comment by BanzaiMan** [comment]
Is this still a problem? I see that 0.13.0 was successfully deployed (https://travis-ci.org/edx/edx-enterprise/jobs/191694132#L538), but with 2.7, due to [a lax deployment condition](https://github.com/edx/edx-enterprise/blob/469f2c8e770f77f793c78be18be34f6e572c22a7/.travis.yml#L53-L55).

**Comment by steenzout** [comment]
@BanzaiMan [here](https://travis-ci.org/Storj/storj-python-sdk/jobs/2304547800 is a fresh new problem:

```
Collecting requests>=2.5.0 (from twine)
  Using cached requests-2.14.0-py2.py3-none-any.whl
  Exception:
  Traceback (most recent call last):
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/commands/install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/req/req_set.py", line 436, in prepare_files
      req_to_install.extras):
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2496, in requires
      dm = self._dep_map
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2697, in _dep_map
      self.__dep_map = self._compute_dependencies()
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2730, in _compute_dependencies
      common = frozenset(reqs_for_extra(None))
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2727, in reqs_for_extra
      if req.marker_fn(override={'extra':extra}):
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/_vendor/_markerlib/markers.py", line 113, in marker_fn
      return eval(compiled_marker, environment)
    File "<environment marker>", line 1, in <module>
  NameError: name 'platform_system' is not defined
```

```
sh: 1: twine: not found
```

**Comment by BanzaiMan** [comment]
@steenzout Your link seems to point to a wrong build. Please double check it.

**Comment by steenzout** [comment]
@BanzaiMan fixed: https://travis-ci.org/Storj/storj-python-sdk/jobs/230454780

**Comment by BanzaiMan** [comment]
@steenzout Right. `pypi` deployment requires `sudo` at the moment, and your build is running on a container, which does not allow use of it (https://travis-ci.org/Storj/storj-python-sdk/jobs/230454780#L295). This I think is a separate issue from this one, however; please open a new issue.

**Comment by BanzaiMan** [comment]
I've pushed an experimental fix to address this issue. Please try it with:

```yaml
deploy:
  provider: pypi
  edge:
    branch: twine-user-install
  ⋮ # rest
```

and report the results.

Thank you!

**Comment by erichiggins** [comment]
Just came across this issue when [my Python package failed to deploy using the built-in TravisCI method](https://travis-ci.org/erichiggins/gaek/jobs/313237680).  Is this experimental fix still required, or can it be made the default?

**Comment by BanzaiMan** [comment]
No one has reported the results, so I am not sure if it works.

**Comment by erichiggins** [comment]
@BanzaiMan I tried by just merging the change to `.travis.yml` into my master branch, but it didn't kick off a build because it wasn't a tagged release.

Frankly, I'm reluctant to add another version tag on my project that's used by others to test this for you. Others may be as well. You may want to create a quick blank pypi project for the sake of confirming it yourself.

**Comment by pierre-rouanet** [comment]
Hi @BanzaiMan!

I have modified my .travis.yml file to your fix but it seems it is still broken: https://travis-ci.org/pollen-robotics/pyluos/jobs/341795364
