### ISSUE TITLE
xcode8.2: Duplicate simulators for iOS 10.2

### ISSUE THREAD

**Issue by tiwoc** [travis-ci/travis-ci#7031]
`xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE' test [...]` fails since switching from `xcode8` to `xcode8.2` with the error message

```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:latest, name:iPhone SE }
	The requested device could not be found because multiple devices matched the request.
	Available destinations for the "Poltergeist Beta" scheme:

[...]

{ platform:iOS Simulator, id:4C741B6B-7647-4DD6-84A0-A71F44552573, OS:10.0, name:iPhone SE }
{ platform:iOS Simulator, id:8F22171A-FD13-45C9-A45B-68529E1385BD, OS:10.1, name:iPhone SE }
{ platform:iOS Simulator, id:63A0BA5F-3911-496F-BF2E-512830B4AD7F, OS:10.2, name:iPhone SE }
{ platform:iOS Simulator, id:DB794781-65A7-4884-8D00-AAC3CBD39A44, OS:10.2, name:iPhone SE }
```

Every device, including the requested iPhone SE, has two iOS 10.2 instances, so that xcodebuild doesn't know which one to select. As a workaround, we can use the 10.1 simulator by invoking `-destination 'platform=iOS Simulator,name=iPhone SE,OS=10.1'`, but it would be nice if the duplicate simulator instances could be removed.

**Comment by tamastimar** [comment]
Temporary fix can be referencing one of the duplicates by id:

`"platform=iOS Simulator,id=DB794781-65A7-4884-8D00-AAC3CBD39A44,OS=10.2"`

**Comment by cotsog** [comment]
Although not idea, it's also possible to manually delete a duplicated simulator with a snippet similar to this in your .travis.yml file:

```
before_install:
  - xcrun simctl delete DB794781-65A7-4884-8D00-AAC3CBD39A44
```

We will update this issue when it's fixed at the image level.

Thank you for your patience.

**Comment by guofengld** [comment]
xcode8.1 and OS=10.1 solved my problem.

**Comment by loudmouth** [comment]
Is there any update for this?

**Comment by jonah-williams** [comment]
Running `xcrun instruments -s devices` will list the available devices and shows that this remains a problem in the current `xcode8.2` image. I used that to locate and specify specific device ids as a workaround in my test matrix:

`xcodebuild -workspace ... -scheme ... -sdk ... -destination "platform=iOS Simulator,OS=$IOS_VERSION,id=$DEVICE_ID" build test`

**Comment by jonah-williams** [comment]
If you're using `fastlane` then you might consider running [`fastlane snapshot reset_simulators`](https://github.com/fastlane/fastlane/tree/master/snapshot#completely-reset-all-simulators) to reset and rebuild the image state but it seems a shame to need to defensively do so on each test run.

**Comment by k06a** [comment]
@jonah-williams thanks, used this way:
```
before_install:
- fastlane snapshot reset_simulators --force
```

**Comment by cocoahero** [comment]
Any update on this @cotsog?

**Comment by tiwoc** [comment]
With the `xcode8.3` image, the duplicate simulators for 10.2 are still there. The 10.3 simulators however are fine. Excerpt from `xcrun simctl list`:

```
-- iOS 10.2 --
    iPhone 5 (D0257C83-DB81-4567-93EC-4C6DF23DC24C) (Shutdown)
    iPhone 5 (5555EE5F-D4E7-4997-8EEA-41A93B41F3AF) (Shutdown)
    iPhone 5s (79C525D3-2383-4201-AC3A-81810F9F4E03) (Shutdown)
    iPhone 5s (2AAA645C-1882-4F81-B866-6241B900C185) (Shutdown)
    iPhone 6 (1FD54EA7-5A25-4D6F-8599-D6F7687DA4EE) (Shutdown)
    iPhone 6 (AD8E8C76-910E-437D-88C2-4D6F6EBE3355) (Shutdown)
    iPhone 6 Plus (EB1167CF-3545-44BC-9D95-482D286F6C66) (Shutdown)
    iPhone 6 Plus (540CDF74-5FF3-488E-8AEB-79D16AB7517D) (Shutdown)
    [...]
-- iOS 10.3 --
    iPhone 5 (048416AC-53FF-42C8-AB92-43C10013E2A4) (Shutdown)
    iPhone 5s (F1C34700-BA52-438C-B5D1-542E949186BF) (Shutdown)
    iPhone 6 (FEFC43F3-126B-48E4-9232-0FC447E9C9D8) (Shutdown)
    iPhone 6 Plus (2A7CE500-22C2-4C40-9BD2-798343FDD285) (Shutdown)
    [...]
```

**Comment by cocoahero** [comment]
@tiwoc looks like they're fixing it soon. See here: https://github.com/travis-ci/travis-ci/issues/7532

**Comment by solarce** [comment]
I have a new image, that I believe is fixed, using a small ruby script, https://github.com/travis-infrastructure/osx-image-bootstrap/pull/20/files

But since simulator stuff isn't something we have a ton of experience with poking at, I have published it with a special key for some testing before promoting it to the main stable images.

The new image names are:
 - `osx_image: xcode8.2simfix` - I confirmed the simulator list no longer has duplicated under 10.2, https://travis-ci.org/solarce/osx-tests/jobs/218313786#L496-L510

**Comment by calebd** [comment]
The 8.2 simulator fix image fixes the duplicate iOS 10.2 simulators issue!

**Comment by jonah-williams** [comment]
@solarce that scripts reads as reasonable to me, looks like you're reimplementing behavior from https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/reset_simulators.rb#L46 if aren't already using that as a reference for how to manage device combinations (I'm assuming fastlane doesn't create invalid combinations).

**Comment by solarce** [comment]
@jonah-williams it appears so, googling led me to a gist that I made a copy of. I'm going to add using `fastlane` instead to how we integrate this step into future image updated. thanks for the tip.

**Comment by solarce** [comment]
Since we have successful reports from users and our own testing looks good, I am going to close this issue. I'm sorry that it's gone on this long and we'll be incorporating how this was resolved into the process for future updates.

**Comment by solarce** [comment]
The image has been promoted to production, https://blog.travis-ci.com/2017-04-05-xcode-82-83-duplicate-simulator-fixes. The `simfix` images will be removed momentarily.

**Comment by russbishop** [comment]
`xcrun simctl list` is the supported way to get the list of Simulators. 

`xcrun simctl delete unavailable` will remove devices for run times you no longer have. 

Duplicates are created by trying to run multiple versions of Xcode simultaneously. 

To delete all devices and let Xcode recreate them just delete `~/Library/Developer/CoreSimulator` then `sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService`.

**Comment by solarce** [comment]
@russbishop thanks for the information. Are you currently seeing any issues with duplicates or just offering some suggestions to help resolve the original issue?

**Comment by emaloney** [comment]
This is still an issue with watchOS under the Xcode 8.3 image. I have [a build failing here](https://travis-ci.org/emaloney/MBToolbox/builds/219161787). Digging into the logs, the relevant bit is:

In the past, I've worked around the problem by switching to another device/OS combo that isn't duplicated. However, that's not possible in this case because _all_ watchOS simulators are duplicated:

```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:watchOS Simulator, OS:3.2, name:Apple Watch Series 2 - 42mm }
	The requested device could not be found because multiple devices matched the request.
	Available destinations for the "MBToolbox" scheme:
		{ platform:macOS, arch:x86_64 }
		{ platform:tvOS Simulator, id:0B24ECED-830A-4F32-8FBE-491718B04246, OS:9.0, name:Apple TV 1080p }
		{ platform:tvOS Simulator, id:13DCC111-2B2D-4D5C-ADE4-FF34E4E8B90C, OS:9.1, name:Apple TV 1080p }
		{ platform:tvOS Simulator, id:98F5318F-0544-40A2-9F2E-E97BFC24A04E, OS:9.2, name:Apple TV 1080p }
		{ platform:tvOS Simulator, id:6B1947F1-0C48-4168-8BAC-B9FF4D982973, OS:10.0, name:Apple TV 1080p }
		{ platform:tvOS Simulator, id:95EC8F7C-5C48-4DD2-A61B-95F2CAAEFB3C, OS:10.1, name:Apple TV 1080p }
		{ platform:tvOS Simulator, id:DA272ADF-D0A3-4F0A-8F81-32D1CB993197, OS:10.2, name:Apple TV 1080p }
		{ platform:watchOS Simulator, id:E6EB5312-ECE7-4669-B470-18EC8B489941, OS:2.0, name:Apple Watch - 38mm }
		{ platform:watchOS Simulator, id:1888BEA9-BFE9-4607-BCB8-6117A1B5A067, OS:2.1, name:Apple Watch - 38mm }
		{ platform:watchOS Simulator, id:2735D344-19AD-404B-A0EA-B626D3D12161, OS:2.2, name:Apple Watch - 38mm }
		{ platform:watchOS Simulator, id:35AB3F5D-069B-4B51-B04B-F6AD78C3041E, OS:3.2, name:Apple Watch - 38mm }
		{ platform:watchOS Simulator, id:38C891AB-EC79-43E4-9311-6FDEB12DCF11, OS:3.2, name:Apple Watch - 38mm }
		{ platform:watchOS Simulator, id:2997632B-4368-4269-9C73-C99AC019BC49, OS:2.0, name:Apple Watch - 42mm }
		{ platform:watchOS Simulator, id:BAD261E2-C227-4E4F-9946-E500DB74C442, OS:2.1, name:Apple Watch - 42mm }
		{ platform:watchOS Simulator, id:80BFFE38-A266-4115-A694-81552DE576FC, OS:2.2, name:Apple Watch - 42mm }
		{ platform:watchOS Simulator, id:644B67CA-F6BA-4DE5-A826-CA96D88E3C0C, OS:3.2, name:Apple Watch - 42mm }
		{ platform:watchOS Simulator, id:BE78B202-BB77-4DC8-A6F0-0F648DA89B4A, OS:3.2, name:Apple Watch - 42mm }
		{ platform:watchOS Simulator, id:3A12376B-EDE6-48DC-B8E0-CDA704E9D423, OS:3.2, name:Apple Watch Series 2 - 38mm }
		{ platform:watchOS Simulator, id:9DF64E1A-A613-4523-A9B7-B98376154190, OS:3.2, name:Apple Watch Series 2 - 38mm }
		{ platform:watchOS Simulator, id:25EF4763-1942-4A3B-A80F-FC080592B82C, OS:3.2, name:Apple Watch Series 2 - 42mm }
		{ platform:watchOS Simulator, id:D5912402-77B7-44B8-93FD-B00406F46415, OS:3.2, name:Apple Watch Series 2 - 42mm }
		{ platform:iOS Simulator, id:B06565DD-EFE5-4F22-8E9D-4DD57A9CB8A4, OS:9.0, name:iPad 2 }
		{ platform:iOS Simulator, id:7121423E-7D04-498A-BE91-DB6FC9AC25A7, OS:9.1, name:iPad 2 }
		{ platform:iOS Simulator, id:6E3CD632-D669-48F1-8EA8-CDCFD67F7D20, OS:9.2, name:iPad 2 }
		{ platform:iOS Simulator, id:1365C892-13B1-4063-8C6E-12236496F498, OS:9.3, name:iPad 2 }
		{ platform:iOS Simulator, id:82827882-8716-4B9C-B3DB-D43461A9C2ED, OS:9.0, name:iPad Air }
		{ platform:iOS Simulator, id:D96A5B22-FF4D-4247-AC2B-A7FC0DE34D4A, OS:9.1, name:iPad Air }
		{ platform:iOS Simulator, id:39D390E7-D483-4685-9617-B16CE893CBC6, OS:9.2, name:iPad Air }
		{ platform:iOS Simulator, id:DE3B3543-5837-4C94-96AC-B06A7017D2EB, OS:9.3, name:iPad Air }
		{ platform:iOS Simulator, id:861252C7-F0D6-4E54-ACD8-048A0AC91E66, OS:10.0, name:iPad Air }
		{ platform:iOS Simulator, id:007B91D6-246D-4FFE-AAA9-D146FB8DD41F, OS:10.1, name:iPad Air }
		{ platform:iOS Simulator, id:0DA678E6-F726-4E58-A871-C44E204F4EA1, OS:10.2, name:iPad Air }
		{ platform:iOS Simulator, id:4C0A3FDF-AEF6-4C59-B7FD-94B53D7AE8EA, OS:10.3, name:iPad Air }
		{ platform:iOS Simulator, id:58D5BB8C-AB74-4494-936E-63E3BC831579, OS:9.0, name:iPad Air 2 }
		{ platform:iOS Simulator, id:6BF3604C-C9A0-4EDE-94A5-E73C82BEF943, OS:9.1, name:iPad Air 2 }
		{ platform:iOS Simulator, id:2FA3299F-C5F5-45EC-946D-06078EA9F26E, OS:9.2, name:iPad Air 2 }
		{ platform:iOS Simulator, id:A7403AE0-896F-4EED-93F5-B1A9179C6834, OS:9.3, name:iPad Air 2 }
		{ platform:iOS Simulator, id:E0735828-E315-4AD1-817D-08722942A39C, OS:10.0, name:iPad Air 2 }
		{ platform:iOS Simulator, id:520395A5-4C51-4567-AB7C-0D5898C43D17, OS:10.1, name:iPad Air 2 }
		{ platform:iOS Simulator, id:B28C52D6-0D8E-4FE3-B0D7-E5BD3B70379C, OS:10.2, name:iPad Air 2 }
		{ platform:iOS Simulator, id:4921C5C7-BD8E-4363-9AB6-07F8449D48D2, OS:10.3, name:iPad Air 2 }
		{ platform:iOS Simulator, id:C904CEFC-192E-41C7-A90F-9D02EEC43A86, OS:10.0, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:620B6747-6DE9-474A-9B37-D4640866FF98, OS:10.1, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:2DE08267-2ECD-48C9-AE79-B90378B49480, OS:10.2, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:C3EDCDF4-04F0-4F04-9099-C4CA064174D0, OS:10.3, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:01E318D1-B15D-41CF-92AA-4A1C79786731, OS:9.1, name:iPad Pro (12.9-inch) }
		{ platform:iOS Simulator, id:877A8DB4-6A51-4572-970B-AD452F12E285, OS:9.2, name:iPad Pro (12.9-inch) }
		{ platform:iOS Simulator, id:378B5A54-13CC-4D08-BC26-E6CB922A6DC6, OS:9.3, name:iPad Pro (12.9-inch) }
		{ platform:iOS Simulator, id:C0857DEA-7725-4C09-ABC3-7A107518DD19, OS:10.0, name:iPad Pro (12.9-inch) }
		{ platform:iOS Simulator, id:C21C8647-9A49-4DF9-A5EA-E170B92FD08A, OS:10.1, name:iPad Pro (12.9-inch) }
		{ platform:iOS Simulator, id:AF27C226-30E2-44D6-B1E6-C2406210F49C, OS:10.2, name:iPad Pro (12.9-inch) }
		{ platform:iOS Simulator, id:4C910228-7C2C-4DBF-9A60-E66613143B9D, OS:10.3, name:iPad Pro (12.9-inch) }
		{ platform:iOS Simulator, id:74A13FC3-9DA1-4C7A-8357-2B62A5AEF782, OS:9.0, name:iPad Retina }
		{ platform:iOS Simulator, id:1E30B263-5206-467C-9DA9-A5378D755980, OS:9.1, name:iPad Retina }
		{ platform:iOS Simulator, id:BF6897D1-D34F-4887-AF75-4DBCC98F99BB, OS:9.2, name:iPad Retina }
		{ platform:iOS Simulator, id:5EF21403-CA7C-4444-B11A-3A3364DDBFC5, OS:9.3, name:iPad Retina }
		{ platform:iOS Simulator, id:FD801F50-AA72-404E-998F-1B3DB3266C26, OS:9.0, name:iPhone 4s }
		{ platform:iOS Simulator, id:1EDAB492-7A51-4207-BDBE-8A1DF3D57555, OS:9.1, name:iPhone 4s }
		{ platform:iOS Simulator, id:60683C7E-374C-45C1-BF24-42FC31A59A24, OS:9.2, name:iPhone 4s }
		{ platform:iOS Simulator, id:3425D3F7-2ECD-4CAA-B695-5717C5F86192, OS:9.3, name:iPhone 4s }
		{ platform:iOS Simulator, id:7FAFDAFD-05CE-4B7F-A8FD-6A04C07BDCA4, OS:9.0, name:iPhone 5 }
		{ platform:iOS Simulator, id:0043A3A8-43CA-42CD-8042-4A4BFCC10D1A, OS:9.1, name:iPhone 5 }
		{ platform:iOS Simulator, id:1C1D29F6-9609-48CE-AD63-2553B580A4FF, OS:9.2, name:iPhone 5 }
		{ platform:iOS Simulator, id:4EFC331E-B4F1-4FCD-AC4E-79584FD6F225, OS:9.3, name:iPhone 5 }
		{ platform:iOS Simulator, id:AC58A864-5E2F-41B7-8AF8-D21711CF981A, OS:10.0, name:iPhone 5 }
		{ platform:iOS Simulator, id:CACEF184-8F22-43F0-AA71-F4B5B8B0E762, OS:10.1, name:iPhone 5 }
		{ platform:iOS Simulator, id:BB2E880B-211B-4681-9833-4ECF5C54532F, OS:10.2, name:iPhone 5 }
		{ platform:iOS Simulator, id:33C19095-4FB7-4035-8962-3D92BF2CDE39, OS:10.3, name:iPhone 5 }
		{ platform:iOS Simulator, id:B5CBE0E2-365E-4E0F-A633-653A14574859, OS:9.0, name:iPhone 5s }
		{ platform:iOS Simulator, id:39580279-B85D-4717-BFE6-9FE88309EEC9, OS:9.1, name:iPhone 5s }
		{ platform:iOS Simulator, id:2FE5E86B-9283-4429-92C1-93C067FD43D2, OS:9.2, name:iPhone 5s }
		{ platform:iOS Simulator, id:85420232-494F-4BBC-925B-DB8F7B53B8F0, OS:9.3, name:iPhone 5s }
		{ platform:iOS Simulator, id:781081B3-B4D4-49D1-B24D-13A3474D4012, OS:10.0, name:iPhone 5s }
		{ platform:iOS Simulator, id:C2E93FD5-F46F-4179-BDBE-E64FE9667472, OS:10.1, name:iPhone 5s }
		{ platform:iOS Simulator, id:33716B1E-8D6C-414B-A916-A259EE9DA5A8, OS:10.2, name:iPhone 5s }
		{ platform:iOS Simulator, id:2F65AAFC-3930-49EF-A6D7-7BF9C1EF4330, OS:10.3, name:iPhone 5s }
		{ platform:iOS Simulator, id:12F77B41-F025-4FED-8C9F-11919855A550, OS:9.0, name:iPhone 6 }
		{ platform:iOS Simulator, id:F197C69A-D8BF-41D8-B9AF-930EAA7A6254, OS:9.1, name:iPhone 6 }
		{ platform:iOS Simulator, id:3BCC1C70-7DEF-4004-92A0-4D6106B514D5, OS:9.2, name:iPhone 6 }
		{ platform:iOS Simulator, id:5FC8A9BF-DE3D-4ED7-9982-316DD5965A7F, OS:9.3, name:iPhone 6 }
		{ platform:iOS Simulator, id:A1F99D34-88BC-4694-B839-435BA2F1EB85, OS:10.0, name:iPhone 6 }
		{ platform:iOS Simulator, id:5D4CCDA5-4DAD-4791-BCF3-08052286003B, OS:10.1, name:iPhone 6 }
		{ platform:iOS Simulator, id:D1BF0A5A-7653-42A0-A508-000106F327E4, OS:10.2, name:iPhone 6 }
		{ platform:iOS Simulator, id:4789D159-0E2C-4F37-BEAB-0CC149992129, OS:10.3, name:iPhone 6 }
		{ platform:iOS Simulator, id:D8B567E5-B269-4EF4-9497-976EBCF20D65, OS:9.0, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:ED5984CD-5642-4E39-AAAD-A49ADACA97A8, OS:9.1, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:627D44AC-2E3D-400C-8F45-6B4625B4A818, OS:9.2, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:5083AF94-3039-480C-BB83-A69E24906558, OS:9.3, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:CBE23103-A502-4F93-9297-45CD5FE96338, OS:10.0, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:B6D6133B-2685-40E8-A26F-DCE844BA9065, OS:10.1, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:271DF4DD-D1BC-4448-9150-EEF6E3DD202D, OS:10.2, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:43EF403C-A2F1-4006-B18E-E252B649D052, OS:10.3, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:B963A4A0-002D-49C9-B9DE-D1790C91A30D, OS:9.0, name:iPhone 6s }
		{ platform:iOS Simulator, id:5BBDA454-3933-40E7-9E1B-29C6F4232DDF, OS:9.1, name:iPhone 6s }
		{ platform:iOS Simulator, id:F5F3A1E6-5699-43E9-9329-409B03ED1F29, OS:9.2, name:iPhone 6s }
		{ platform:iOS Simulator, id:FF0925F1-776F-40B6-893A-4D1ED7AD5EFE, OS:9.3, name:iPhone 6s }
		{ platform:iOS Simulator, id:85434D99-0342-4AD1-BDA3-898B477DFE4A, OS:10.0, name:iPhone 6s }
		{ platform:iOS Simulator, id:50983404-E9A6-47E1-85AC-38C6928F3F60, OS:10.1, name:iPhone 6s }
		{ platform:iOS Simulator, id:E4E54157-AC93-4404-9501-C12A72518F6B, OS:10.2, name:iPhone 6s }
		{ platform:iOS Simulator, id:9E919F18-6EBF-4693-B0F2-9DA4212D4DC7, OS:10.3, name:iPhone 6s }
		{ platform:iOS Simulator, id:54676E97-04B9-4EDB-A2CA-17B4AA16279F, OS:9.0, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:B5ED9ADB-42AF-4B1F-B21C-574D95CABB6C, OS:9.1, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:A07A1CAF-93CF-4D6A-B6BE-C85CA71E3ACD, OS:9.2, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:130C6939-F7DF-4F39-8679-FC6C82779B38, OS:9.3, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:F502543D-FBBF-4F9F-9A0C-D0ACD9461AC7, OS:10.0, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:BF414481-FFB0-4B72-8B23-6116EA219F69, OS:10.1, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:AE8F60CE-F1D2-4E16-89B1-07259BAEA2E8, OS:10.2, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:EE3BD3BF-1F67-4E59-84C5-F6A1EF84AF11, OS:10.3, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:A4E071FE-4261-4738-95EC-C3EFE9BDFFF6, OS:10.0, name:iPhone 7 }
		{ platform:iOS Simulator, id:F7851212-422F-4E19-9492-D2A049D269CB, OS:10.1, name:iPhone 7 }
		{ platform:iOS Simulator, id:3792DF18-A95C-4E13-8C59-85DF9C82806B, OS:10.2, name:iPhone 7 }
		{ platform:iOS Simulator, id:57E7D476-3A98-4107-A64D-98CA0EA13EC0, OS:10.3, name:iPhone 7 }
		{ platform:iOS Simulator, id:D9A44B2B-0B7D-4253-8839-9C377DB47000, OS:10.0, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:C773797A-6136-4854-A810-BC44A16E9073, OS:10.1, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:70BEC49F-1E8A-4283-92E8-FFC2DB5CC915, OS:10.2, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:375B606D-0484-4067-9E45-7697A3860886, OS:10.3, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:3C56E00B-46F9-4340-8078-BD49420A1649, OS:9.3, name:iPhone SE }
		{ platform:iOS Simulator, id:1052B9E1-F7D2-4B3B-A211-31C82FD1B2F2, OS:10.0, name:iPhone SE }
		{ platform:iOS Simulator, id:7B653600-0BB7-431C-93A0-38E2E16057AC, OS:10.1, name:iPhone SE }
		{ platform:iOS Simulator, id:2F4687F6-DFB0-4658-9813-BA965BBB962E, OS:10.2, name:iPhone SE }
		{ platform:iOS Simulator, id:3C358901-B375-4F3E-87D9-B7FF56CBEFE5, OS:10.3, name:iPhone SE }
```

**Comment by ikesyo** [comment]
@emaloney I already filed #7580.
