### ISSUE TITLE
R-travis: error when installing dependencies: "ERROR: no packages specified"

### ISSUE THREAD

**Issue by drisso** [travis-ci/travis-ci#7576]
Dear @craigcitro and @jimhester.

I'm seeing the following error when installing and checking the [clusterExperiment](https://github.com/epurdom/clusterExperiment) package (cc @epurdom).

```
trying URL 'https://cloud.r-project.org/src/contrib/abind_1.4-5.tar.gz'
Content type 'application/x-gzip' length 21810 bytes (21 KB)
==================================================
downloaded 21 KB

Installing abind
Running command /home/travis/R-bin/lib/R/bin/R 
Arguments:
CMD
INSTALL
'/tmp/Rtmp28daE3/devtools3edc4dd74d7d/abind'

Warning: invalid package â€˜'/tmp/Rtmp28daE3/devtools3edc4dd74d7d/abind'â€™
Error: ERROR: no packages specified
Installation failed: NULL : Command failed:
  
 Warning: invalid package â€˜'/tmp/Rtmp28daE3/devtools3edc4dd74d7d/abind'â€™
Error: ERROR: no packages specified
```

This error is repeated many times for all the dependencies that it tries to install, I presume. The full log is here: https://s3.amazonaws.com/archive.travis-ci.org/jobs/218910640/log.txt

It ends with the following error:

```
missing: abind, ade4, ape, bold, colorspace, crul, data.table, DBI, dendextend, DEoptimR, dichromat, diptest, doParallel, dplyr, flexmix, foreach, fpc, GenomeInfoDb, GenomicRanges, ggplot2, gridBase, gridExtra, gtable, howmany, httpcode, IRanges, iterators, kernlab, labeling, limma, locfdr, MAST, matrixStats, mclust, modeltools, munsell, mvtnorm, natserv, NMF, phylobase, pkgmaker, plyr, prabclus, prettyunits, progress, RColorBrewer, registry, rentrez, reshape, reshape2, ritis, rncl, RNeXML, rngtools, robustbase, rotl, rredlist, S4Vectors, scales, solrium, SummarizedExperiment, taxize, tibble, tidyr, triebeard, trimcluster, urltools, uuid, viridis, viridisLite, worrms, xtable, XVector, zlibbioc

travis_time:end:15835d73:start=1491404781230721022,finish=1491405880231069963,duration=1099000348941
[0K
[31;1mThe command "Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .[0m

Your build has been stopped.
```

I've tried to remove the cached packages, in case that was a problem, but it didn't solve it.

The [.travis.yml file](https://github.com/epurdom/clusterExperiment/blob/master/.travis.yml) is the same that we have been using for some time and never resulted in these errors.

Any idea of what's going on? Any help will be much appreciated!

**Comment by jimhester** [comment]
It looks like a change in devel devtools has broke something. I would use CRAN devtools in the meantime, i.e. take out https://github.com/epurdom/clusterExperiment/blob/10cb9ba33198172979044fbd0e26e04da06a0e1f/.travis.yml#L32-L34

**Comment by drisso** [comment]
Thank you for the quick reply. I also suspected that it was an issue with the devel devtools package, but unfortunately, the CRAN version of devtools give us a different error:

```{r}
Installing diagram
Error in FUN(X[[i]], ...) : 
  Invalid comparison operator in dependency: >= 
```

which I believe is a known issue addressed in the devel version.

**Comment by jimhester** [comment]
Ah yes, if you go back a few commits in the devtools version you install it should work then.

```yaml
## Use patched devtools
r_github_packages:
  - hadley/devtools@efa894ffa
```

**Comment by drisso** [comment]
Thank you, @jimhester ! Going back to that commit, everything works!

**Comment by BanzaiMan** [comment]
Looks like we can close this.

**Comment by f0nzie** [comment]
still getting these issues with Travis and devtools. Should I use the same commit `efa894ffa`?

**Comment by f0nzie** [comment]
Not good (getting this from Travis) in two packages:

```
missing: rhdf5, S4Vectors
The command "Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
missing: rhdf5, S4VectorsThe command "Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { 
```message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
