### ISSUE TITLE
Process continue running even after "Done. Your build exited with 0."

### ISSUE THREAD

**Issue by fernando-andrade-pereira** [travis-ci/travis-ci#7702]
My builds suddenly stopped working. Even after after the message "Done. Your build exited with 0.", the build continue running and I get 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

No build I tried to run today passed

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by fernando-andrade-pereira** [comment]
https://travis-ci.com/ZXVentures/courier-api/builds/45351882

**Comment by BanzaiMan** [comment]
Thanks for the information. We are looking into this.

**Comment by flpStrri** [comment]
Any update on it?

**Comment by Grynn** [comment]
Hey! We've the same issue
Paying customers from >1 yr now. Please fix.

**Comment by flpStrri** [comment]
@BanzaiMan you got any updates on it? We are still having this problems on our builds.

**Comment by Grynn** [comment]
We did not get any response/support from Travis, though we fixed the issue by adding this line to .travis.yml
`after_script: sudo service mysql stop`

**Comment by BanzaiMan** [comment]
Hello, we've deployed a few changes which may caused this problem.

Could you tell us if the issue is persisting now (starting around 2017-07-18T15:06:06Z)?

Thanks.

**Comment by BanzaiMan** [comment]
And if the issue persists, do include build log URL. Thanks again.

**Comment by flpStrri** [comment]
Yes! It got fixed! 😃

**Comment by sc0ttkclark** [comment]
Still having this issue on our builds. Using 'trusty' build.

Can't send the build URL as it's private, I could e-mail it though.
