### ISSUE TITLE
New Dynamic Haskell installation broken

### ISSUE THREAD

**Issue by hvr** [travis-ci/travis-ci#7752]
The new feature as implemented via travis-ci/travis-build#916 appears to be broken;

I created a trivial `.travis.yml` file containing

```yaml
language: haskell

ghc: 8.2.1
```

which failed to actually install the GHC version as can be seen on https://travis-ci.org/hvr/netrc/builds/231649622#L136

```
[0K[33;1mghc-8.2.1 is not installed; attempting installation[0m

[32;1mAdding ppa:hvr/ghc.[0m
Usage: apt-add-repository <sourceline>

apt-add-repository is a script for adding apt sources.list entries. 
It can be used to add any repository and also provides a shorthand 
syntax for adding a Launchpad PPA (Personal Package Archive)
repository.

<sourceline> - The apt repository source line to add. This is one of:
  a complete apt line in quotes, 
  a repo url and areas in quotes (areas defaults to 'main')
  a PPA shortcut.

  Examples:
    apt-add-repository 'deb http://myserver/path/to/repo stable myrepo'
    apt-add-repository 'http://myserver/path/to/repo myrepo'
    apt-add-repository 'https://packages.medibuntu.org free non-free'
    apt-add-repository http://extras.ubuntu.com/ubuntu 
    apt-add-repository ppa:user/repository

If --remove is given the tool will remove the given sourceline from your
sources.list


apt-add-repository: error: no such option: -q
```

**Comment by BanzaiMan** [comment]
Hello. I deployed https://github.com/travis-ci/travis-build/pull/1052 to staging. Could you test it?

**Comment by hvr** [comment]
@BanzaiMan sure, I'm already on it.

**Comment by hvr** [comment]
@BanzaiMan After a bit of testing it appears that the PR fixes the immediate problem (i.e. now `ghc` and `cabal` get installed as expected). However, the `PATH` is not set up accordingly, so this is still not working as expected!

There's two ways to set the PATH properly for the ghc/cabal packages from my PPA, either 

 - add `/opt/ghc/bin` in front of `PATH`; this will provide access to the `cabal` as well as the various `ghc` toolchain executables; **or**

 - add `/opt/ghc/$GHCVER/bin` **and** `/opt/cabal/$CABALVER/bin` to the PATH.

I strongly suggest to use the former one (i.e. `/opt/ghc/bin`) as that's more reliable/less error-prone (especially since the current script just carries on with some default compiler version, thereby making it less obvious that something went wrong trying to install the requested ghc/cabal versions)

**Comment by BanzaiMan** [comment]
@hvr The current setup prepends `${TRAVIS_GHC_ROOT}/${TRAVIS_HASKELL_VERSION}/bin` to `$PATH`. Should `/opt/ghc/bin` appear before or after it?

https://github.com/travis-ci/travis-build/blob/b0d3b73431e890fd370a8cdc8a0f8bd42e7ba311/lib/travis/build/script/haskell.rb#L37

The order in which these job phases (such as `travis_run_configure()`) is somewhat of implementation detail (and it may change in the future), but I can say that this particular one happens very early in the job, before any additional package is installed.

**Comment by hvr** [comment]
@BanzaiMan `/opt/ghc/bin` should be prepended; that way any ghc/cabal installed via my PPA  takes precedence.

**Comment by BanzaiMan** [comment]
Fixed `$PATH`, but I still see 8.0.2 after a successful installation of 8.2.1. https://staging.travis-ci.org/BanzaiMan/travis_staging_test/jobs/584181#L471

**Comment by hvr** [comment]
@BanzaiMan I'll take a look

**Comment by hvr** [comment]
@BanzaiMan ok, now I see what the problem is.

So the problem occurs only in the Trusty images, because there you have already a couple of GHC versions pre-installed from my PPA. And `update-alternatives` is used to provide the `/opt/ghc/bin/ghc` symlink. However, since GHC 8.2.1 is still in RC phase, it's got a lower priority in automatic mode than e.g. GHC 8.0.2; that's why the symlink remains pointing to GHC 8.0.2.

So if if you want the Travis image to come preinstalled with a set of popular GHC versions, then the 2nd variant I mentioned in https://github.com/travis-ci/travis-ci/issues/7752#issuecomment-301172545 may actually be better, i.e.

 - add (prepend) /opt/ghc/$GHCVER/bin and /opt/cabal/$CABALVER/bin to the PATH.

In that mode, it would be great to verify that

 -  `/opt/ghc/$GHCVER/bin/ghc` and
 - `/opt/cabal/$CABALVER/bin/cabal` 

actually exist after installing the respective PPA `.deb` packages

**Comment by BanzaiMan** [comment]
There is an invocation of `cabal update`, which appears to set up `$PATH` correctly for `cabal`.

**Comment by hvr** [comment]
@BanzaiMan I assume you're referring to

```
update-alternatives: using /opt/cabal/bin/cabal-2.0 to provide /opt/cabal/bin/cabal (opt-cabal) in auto mode
```

That's because `cabal-2.0` has a higher priority than `cabal-1.24` as can be seen here (taken from https://staging.travis-ci.org/hvr/travisnextgen/builds/584201)

```
update-alternatives --display opt-cabal
opt-cabal - auto mode
  link currently points to /opt/cabal/bin/cabal-2.0
/opt/cabal/bin/cabal-1.24 - priority 12400
  slave opt-ghc-cabal: /opt/cabal/bin/cabal-1.24
/opt/cabal/bin/cabal-2.0 - priority 20000
  slave opt-ghc-cabal: /opt/cabal/bin/cabal-2.0
Current 'best' version is '/opt/cabal/bin/cabal-2.0'.
```

The problem with using `update-alternative` in automated mode is that is that `update-alternative` is set up to prefer the "best" version for the default symlink. But this isn't compatible with what you want here. 

Another alternative would be to manually instruct `update-alternative` which version to set; but I think that's not as easy as the variant I describe in https://github.com/travis-ci/travis-ci/issues/7752#issuecomment-302216057

**Comment by BanzaiMan** [comment]
I was referring to this bit:

```sh-session
$ cabal update
Config file path source is default config file.
Config file /home/travis/.cabal/config not found.
Writing default configuration to /home/travis/.cabal/config
Downloading the latest package list from hackage.haskell.org
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.2.0.20170505
$ cabal --version
cabal-install version 1.24.0.2
compiled using version 1.24.2.0 of the Cabal library 
```

**Comment by hvr** [comment]
@BanzaiMan well, how shall we proceed? shall I test some more? or is there still a problem or anything else you need helper with or information on?

**Comment by hvr** [comment]
@BanzaiMan ping?

**Comment by lwm** [comment]
Sorry to butt in but I'd love to see this fixed! Thanks for the work so far!

**Comment by BanzaiMan** [comment]
Sorry for the long delay. I am planning to take a better look soon.

**Comment by BanzaiMan** [comment]
@hvr My earlier comment about `cabal`'s `$PATH` manipulation may have been inaccurate. I double checked and found something different. https://github.com/travis-ci/travis-build/commit/b1979067d207d3cd8af12857de41cc8b9dba7861

Here's a result: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/jobs/619926#L56

Is that what we should expect?

**Comment by hvr** [comment]
@BanzaiMan I'm not sure. testing for the existence of the `cabal` executable before adding to the path makes sense. But the code should also make sure that if a certain version of `cabal` or `ghc` is requested by the travis.yml file, then the ghc/cabal executables you get resolved via $PATH have the expected `ghc --numeric-version` and `cabal --version` reported...

...and if the reported version does not match the travis specification, the travis job shall fail, as otherwise people likely won't notice that their travis jobs don't test the intended configuration, and think everything's fine (i.e. we'd risk getting an inaccurate "green" build result which should have been "red")

does this make any sense?

**Comment by BanzaiMan** [comment]
Yes, it makes sense.

**Comment by BanzaiMan** [comment]
@hvr I think https://github.com/travis-ci/travis-build/pull/1052 now behaves the way you describe:

1. Install `ghc` and `cabal` packages from ppa:hvr/ghc **exactly when** `ghc: x.y.z` **and** `cabal: x.y`.
1. Terminates in error if `ghc --numeric-version` or `cabal --numeric-version` does not meet the criteria given.

I'll leave it deployed to staging (https://staging.travis-ci.org) for the weekend, so I would appreciate your (or anyone's, really) testing and feedback.

**Comment by hvr** [comment]
@BanzaiMan I've given it a quick test-drive, and it appears to work well, mostly.

a) `cabal` seems to default to "1.22"; this is a bad default for more recent GHCs.

b) ghc:head & cabal:head doesn't work

```yaml
ghc: "head"
```

It does install the proper debian package, i.e.

```
Preparing to unpack .../ghc-head_8.3.20170829+git.0.6f1ccaa-7~14.04_amd64.deb ...
Unpacking ghc-head (8.3.20170829+git.0.6f1ccaa-7~14.04) ...
Setting up ghc-head (8.3.20170829+git.0.6f1ccaa-7~14.04) ...
```

However, it does fail lateron with

```
GHC head not found. Terminating.
```

Similarly, `cabal: "head"` doesn't work either.

See https://staging.travis-ci.org/hvr/travisnextgen/builds/621246

In general, "head" refers to the latest development snapshot, and the reported version is supposed to be one where the 2nd version component is an odd number (e.g. GHC version 8.**3**.20170829, or Cabal version 2.**1**.0.0)

**Comment by BanzaiMan** [comment]
@hvr Thanks for testing.

1. It is easy to fix the default `cabal` version. What is a good choice here?
1. If `head` is wanted, is it permissible to skip the check?

**Comment by hvr** [comment]
@BanzaiMan 

>    It is easy to fix the default cabal version. What is a good choice here?

That's complicated..

In the past, we had a correlation between GHC version and the respective cabal version:

- GHC 8.2 == cabal 2.0
- GHC 8.0 == cabal 1.24
- GHC 7.10 == cabal 1.22
- GHC 7.8 == cabal 1.18
- GHC 7.6 == cabal 1.16
- GHC 7.4 == cabal 1.14
- GHC 7.0 == cabal 1.10

However, ideally the latest `cabal` version *should* be compatible with all stable GHC versions.

Consequently, a better default would be to use `cabal: "2.0"` currently.

And while we're at it; `cabal` is currently transitioning to slightly different build-mode (works starting with cabal-2.0); 

Instead of `cabal install --dep` /  `cabal configure` / `cabal build` / `cabal test`

you'd simply invoke `cabal new-build ---enable-tests all` / `cabal new-test --enable-tests all`

and this new mode is also Travis CI cache friendly; as all you'd need to cache would simply be  in `~/.ghc/` and `~/.cabal/store/`

>    If head is wanted, is it permissible to skip the checks?

yes, I think that's a reasonable pragmatic solution :-)

**Comment by BanzaiMan** [comment]
@hvr Great. `cabal` now defaults to 2.0, and version checks are absent for "head" builds in staging.

If this is working to your satisfaction, we'll deploy it Tuesday (Monday is a US holiday).

**Comment by BanzaiMan** [comment]
The PR has been merged and deployed.

I'm closing this optimistically. If you see problems, do let us know.

**Comment by hvr** [comment]
@BanzaiMan Sorry, only got to testing this now... it works... almost...

if you look at
https://staging.travis-ci.org/hvr/travisnextgen/builds/621246

two jobs failed because while those did manage to have the requested GHC version,  the requested cabal version wasn't provided.

**Comment by BanzaiMan** [comment]
@hvr The current staging does not have this code. Could you test it on production?

**Comment by lwm** [comment]
Are errors [like this](https://travis-ci.org/commercialhaskell/stack/jobs/276544532#L455) as a result of these changes? Butting in again 😅

**Comment by BanzaiMan** [comment]
Does anyone have a reasonable result on production? I think there is a problem with the current production, and https://github.com/travis-ci/travis-build/pull/1237 fixes it, but I'm not 100% certain.

FWIW, https://travis-ci.org/BanzaiMan/travis_production_test/builds/293494167 shows that `ghc: 8.2.1` works. (`ghc: 8.2.2` does not, because the 8.2.2 package has `8.2.1.20170928` and this does not match the expected version string; see https://launchpad.net/~hvr/+archive/ubuntu/ghc/+index?batch=75&memo=75&start=75).

**Comment by hvr** [comment]
@BanzaiMan Yes, `ghc-8.2.2` has version `8.2.1.20170928` because it's not yet the final 8.2.2 release, but rather a release candidate. Once it becomes a release candidate its version will match `8.2.2`. That's the versioning scheme used by the GHC project. Admittedly, it's a bit unfortunate as it complicates the version check. As for the  problem in production you're referring to, I'm not sure I understand; what problem are you referring to specifically? Is there a bug report somewhere?

**Comment by BanzaiMan** [comment]
@hvr Thanks for the explanation.

The "broken"ness comes from my investigation while developing https://github.com/travis-ci/travis-build/pull/1237. According to my analysis (see https://travis-ci.org/travis-ci/travis-build/jobs/292867624#L718), we should be writing a bad bash function around the invocation of `travis_ghc_find`). I have not really confirmed this; I have not been able to reproduce it with the configuration.

**Comment by BanzaiMan** [comment]
I am fairly confident that https://github.com/travis-ci/travis-build/pull/1237 is correct, and should be merged shortly.

Is there anything left to do here on this issue?

**Comment by BanzaiMan** [comment]
I'm closing this optimistically. If you still see issues, do open new issues. 

Thanks.
