### ISSUE TITLE
travis docker version has a bug to support 'shared' flag

### ISSUE THREAD

**Issue by reachlin** [travis-ci/travis-ci#8104]
it seems the docker from travis can't support 'shared' flag for '-v' parameter: https://travis-ci.org/reachlin/k8s0/builds/250671863

i googled it, and seems some certain docker version has this problem, docker/libcontainer#632 please upgrade your docker. thanks.

**Comment by BanzaiMan** [comment]
Until the image is updated, you can update `docker-ce` package yourself.

```yaml
addons:
  packages:
    - docker-ce
```

**Comment by reachlin** [comment]
@BanzaiMan I tried with your advice and the version is 17.03.1-ce. it is still not working https://travis-ci.org/reachlin/k8s0/builds/255923679

**Comment by BanzaiMan** [comment]
@reachlin Sorry, the previous snippet had incorrect data. I fixed it now.

**Comment by reachlin** [comment]
@BanzaiMan no luck, https://travis-ci.org/reachlin/k8s0/builds/257181995

**Comment by BanzaiMan** [comment]
That indicates to me that the latest released version ([17.06.0](https://travis-ci.org/reachlin/k8s0/builds/257181995#L444)) does not have the feature you need.

I'm not sure what else we can suggest here.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/reachlin/k8s0/builds/257183072 shows it's passing. I'm closing this.

**Comment by reachlin** [comment]
it's not fixed, i just removed it on travis, but thanks anyway @BanzaiMan

**Comment by BanzaiMan** [comment]
Is there a version that supports this?

**Comment by reachlin** [comment]
looks like it's not about docker version, there must be sth. different between travis box and local one, still investigating...

**Comment by reachlin** [comment]
@BanzaiMan more details https://github.com/reachlin/k8s0/issues/2
