### ISSUE TITLE
update gimme

### ISSUE THREAD

**Issue by pierrre** [travis-ci/travis-ci#8177]
Hello,

I've noticed a strange issue with Travis + Go 1.9 + gimme v1.0.0 + errcheck (linter).
I've recently updated my project to Go 1.9rc1, and now errcheck fails.
It looks like the tool doesn't recognize the $GOROOT properly.
It uses the "default" $GOROOT in `/usr/local/go`, instead of the one defined by gimme.

If I understand correctly, Travis uses an old gimme version (v1.0.0) which doesn't always set the $GOROOT env variable.
Latest version does https://github.com/travis-ci/gimme/commit/913dd17ff3c853e2fe31f58f4487c078a8b83f7a

On my computer with the latest gimme version, I don't have this issue.

Can you update the gimme version please ?
(I use the trusty environment)

**Comment by pierrre** [comment]
for now my fix is:
```
before_install:
  - export GOROOT=$(go env GOROOT) # see https://github.com/travis-ci/travis-ci/issues/8177
```

**Comment by pierrre** [comment]
FYI, one of my open source project that fails: https://travis-ci.org/pierrre/imageserver/builds/258198221
Go 1.8.3 works fine
Go 1.9rc1 fails (see gometalinter)

**Comment by karalabe** [comment]
We've hit the same issue https://travis-ci.org/ethereum/go-ethereum/jobs/261067035#L508

This actually seems a bug in Go 1.9 that it detects the correct GOROOT, but fails to actually use it internally and defaults to the compilation version https://github.com/golang/go/issues/21313. The Go team apparently won't fix it for the 1.9.x release family.

**Comment by kevinburke** [comment]
Looks like this has been fixed in recent versions of Travis or gimme - Go 1.9 builds complete successfully now without the suggested preamble

**Comment by pdf** [comment]
Still appears broken here.

**Comment by AlekSi** [comment]
I don't think gimme 1.2.0 was deployed to travis-ci.org yet. When can we expect it?

**Comment by pierrre** [comment]
I confirm, it's not yet updated.
I still see gimme 1.0.0
I use:
- private build
- trusty

**Comment by BanzaiMan** [comment]
This has been fixed with https://github.com/travis-ci/travis-build/pull/1154.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/269731191#L434-L435
