### ISSUE TITLE
New Trusty image upgrades postgres to 10.1

### ISSUE THREAD

**Issue by mikeclarke** [travis-ci/travis-ci#8897]
After the Trusty image upgrade, we're encountering a known issue with our version of psycopg2 + postgres 10. Was it anticipated that postgres be upgraded as part of the image upgrade? We didn't see this in the release notes. To fix, we switched to `sudo: required` and specified `group: deprecated-2017Q4` in our travis config.

Thanks!

Related psycopg2 issue: [Error: could not determine PostgreSQL version from '10.1'](https://github.com/psycopg/psycopg2/issues/594)

**Comment by mattrobenolt** [comment]
Was the actual version of Postgres server upgraded? Or just libpq?

**Comment by amercader** [comment]
We are also finding this issue, but Postgres 10.1 is not listed in the build environment:

PG client version: https://travis-ci.org/okfn/rtei/builds/315313300#L99
PG installed versions: https://travis-ci.org/okfn/rtei/builds/315823659#L352

**Comment by matrixise** [comment]
In fact, the issue is libpq, Travis installs the last version of libpq, and this is the reason of your issue.

You can check here: https://travis-ci.org/matrixise/debug-travis#L1032-L1033

And the confirmation is with the output of pg_config --version

https://travis-ci.org/matrixise/debug-travis#L1597

This output is used by the setup.py of psycopg2, it has been fixed in 2.7.x

**Comment by BanzaiMan** [comment]
This might be a packaging issue with PostgreSQL packages. I explore some of the issues in https://github.com/travis-ci/travis-ci/issues/9011#issuecomment-355366295.

**Comment by BanzaiMan** [comment]
In the most recent build image, `libpq-dev` is 10.1, which is responsible for the `pg_config` output.

**Comment by scottanderson42** [comment]
This is still an issue:

```
  dist: trusty
  language: python
  python:
    - "2.7"

  addons:
    - postgresql "9.6"
    - apt:
      packages:
        - postgresql-server-dev-9.6

  before_install:
    - apt-cache policy libpq-dev
```

```
$ apt-cache policy libpq-dev
libpq-dev:
  Installed: 10.1-1.pgdg14.04+1
  Candidate: 10.3-1.pgdg14.04+1
  Version table:
     10.3-1.pgdg14.04+1 500
        500 http://apt.postgresql.org/pub/repos/apt trusty-pgdg/main amd64 Packages
 *** 10.1-1.pgdg14.04+1 100
        100 /var/lib/dpkg/status
     9.3.22-0ubuntu0.14.04 500
        500 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu trusty-security/main amd64 Packages
     9.3.4-1 500
        500 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty/main amd64 Packages
```

We install a specific version of psycopg2 in our requirements.txt, which is failing due to the 10.x version of libpq. While yes, we could update our own psycopg2, we're still getting the wrong version of libpq-dev for PostgreSQL 9.6.

**Comment by duttonw** [comment]
See: https://github.com/ckan/ckan/issues/5310#issuecomment-669593866 

Have managed to get plugins to build with travis bionic image at https://github.com/qld-gov-au/ckanext-qa/pull/7/files
