### ISSUE TITLE
dpl-1.9 fails to authenticate on bintray

### ISSUE THREAD

**Issue by fg2it** [travis-ci/travis-ci#9314]
I didn't change the authentication key (and confirm on Bintray it is still good), so I expect I shouldnot have this deployement problem.
Failing travis log is [here](https://travis-ci.org/fg2it/grafana-on-raspberry/jobs/351003836) (the previous working one, with dpl 1.8.47, is [here](https://travis-ci.org/fg2it/grafana-on-raspberry/builds/347439605))

**Comment by BanzaiMan** [comment]
To revert to the old behavior, please try:

```yaml
deploy:
  edge:
    branch: v1.8.47
  ⋮ # rest
```

**Comment by fg2it** [comment]
Thanks @BanzaiMan. I saw the advice in other issues of the same kind but didn't try it because the syntax is rejected by travis lint (both local ruby client and current weblint). But will try.

**Comment by fg2it** [comment]
For reference, syntax was a bit different in my case since I have multiple deployments : 
```yaml
deploy:
  - edge:
      branch: v1.8.47
    provider: xxx
    # rest
  - edge:
      branch: v1.8.47
    provider: zzz
    # rest
```
I let you close this when it seems right (ie now or if you expect this workaround won't be needed at some point).
Thanks again for your (fast!) help

**Comment by BanzaiMan** [comment]
While troubleshooting, I found that the `bintray` provider is quite unorthodox (not conforming to the convention). I want to rectify this, but it could break existing deployments further, because doing so will introduce the cleanup phase (see https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup).

To test:

```yaml
deploy:
  provider: bintray
  edge:
    branch: bintray-unauth
  skip_cleanup: true # if your deployment relies on build artifacts
  ⋮
```

(Adjust for multi-provider deployment accordingly.)

Thanks.

**Comment by fg2it** [comment]
I try and it fails. I did a bit differently since I triggered the build using the api, not commiting to github.
In fact I perform several tests and to sum up:
- the previous fix (edge/branch v1.8.47) is [working](https://travis-ci.org/fg2it/grafana-on-raspberry/builds/351768337)
- the last fix (edge/branch bintray-unauth) [fails](https://travis-ci.org/fg2it/grafana-on-raspberry/jobs/351768393) with
```
missing url
failed to deploy
```

No really the right spot, but it would be nice to display the `deploy` part of the configuration in the `view config` display of the jobs.

**Comment by BanzaiMan** [comment]
Thanks for the report. I pushed another commit. Could you test it again?

**Comment by igagis** [comment]
would be nice also to see this problem fixed https://github.com/travis-ci/travis-ci/issues/5966

**Comment by BanzaiMan** [comment]
@igagis It's best keep this issue focused on the problem at hand. Thanks.

**Comment by fg2it** [comment]
just did: [failed](https://travis-ci.org/fg2it/grafana-on-raspberry/jobs/352505957) (and branch v1.8.47 [still working](https://travis-ci.org/fg2it/grafana-on-raspberry/jobs/352506670))

**Comment by BanzaiMan** [comment]
@fg2it Sorry for the continued troubles. I've pushed another commit. Could you restart the failing build?

Thank you!

**Comment by BanzaiMan** [comment]
The tag v1.8.47 would not change, so there is no need to report the result.

**Comment by fg2it** [comment]
Hum, mixed feelings [here](https://travis-ci.org/fg2it/grafana-on-raspberry/jobs/352577059). I set up 2 deployments : 
- [first](https://travis-ci.org/fg2it/grafana-on-raspberry/jobs/352577059#L2537) one is deployed correctly
- at the[ second deployment](https://travis-ci.org/fg2it/grafana-on-raspberry/jobs/352577059#L2546), the build just seems to hang and is terminated after 10 min. Last line before hanging is
```bash
Building dpl gem locally with source travis-ci/dpl and branch bintray-unauth
```
which is a bit strange since the [previous one](https://travis-ci.org/fg2it/grafana-on-raspberry/jobs/352577059#L2440) succeed.

**Comment by BanzaiMan** [comment]
Could you reproduce the custom payload you gave to this build?

**Comment by BanzaiMan** [comment]
Also, is the hang reproducible?

**Comment by BanzaiMan** [comment]
I've pushed another commit to the branch.

**Comment by fg2it** [comment]
> Also, is the hang reproducible?

Yes it was : 


> Edit: to check it is not some connection issue I started another [build](https://travis-ci.org/fg2it/grafana-on-raspberry/builds/352594033). But still fails

Here is the deploy step : 
```yaml
deploy:
  - edge:
      branch: bintray-unauth
    provider: bintray
    file: armv7.d
    user: fg2it
    key:
      secure: "FteIGr9J9B93Etvy5PmuAx5cZpB5sCt1Bn7FXf75zcAtWUMQEUHwqc995XrAjPrnFZ9yWMF1kInmRIg8ejbLx0PuBWBhJU60FPwRPm+2M2WM8Shc98DXPIm6A+xKC06yt8rU6/nyYyKrJBEf0kPiOHjnXE4rgqZaLVA+UbfSEuCVclmylxecZYNDvjIVJpDQghp6fCUhMqUjwO9UICZfl9ZhRXBeeZloUhR0qwF9orEtjW8usE6PDWl136tqAqBMQOe06Qz+n9JKPqAKIzdLOrviDKr8uDxA/ZPucuAHYCScq3IuRNwgdzgOKOvlVVDW5+uObEWahKEQHs8e7zC4fKdscq5CsZhuY0rVV8G6UNW3Hj69OL7gefiQ5Bd88QoF0X2/CFPe+5GngehpbMnIAg8iH55pEC5v516w4zaij4lyUlcY/o9foSre8YJaD5UlkfsGCj5HJiOnPLCK6l1rtxVTbol4GYq8+w5kWQhfHzfTp4GzUZuQS12K32kynDt3EV0To3VPpbTxK4+Bdw5BnEo+gYaV9/ynM6BiCqlnNUWi42JzUwpC1MFiesVuEaZ/IgtXeZM9/vnp1WgKZDwqDNfvvv7l+DaLI4h+kx7cgSi6EQraxOLBMu/i76CAh6SXunHIKyIhIo1FbQJ8n2HohTZ6bD3jIbnJz/KEqNkeCyA="
    skip_cleanup: true
  - edge:
      branch: bintray-unauth
    provider: bintray
    file: arm64.d
    user: fg2it
    key:
      secure: "FteIGr9J9B93Etvy5PmuAx5cZpB5sCt1Bn7FXf75zcAtWUMQEUHwqc995XrAjPrnFZ9yWMF1kInmRIg8ejbLx0PuBWBhJU60FPwRPm+2M2WM8Shc98DXPIm6A+xKC06yt8rU6/nyYyKrJBEf0kPiOHjnXE4rgqZaLVA+UbfSEuCVclmylxecZYNDvjIVJpDQghp6fCUhMqUjwO9UICZfl9ZhRXBeeZloUhR0qwF9orEtjW8usE6PDWl136tqAqBMQOe06Qz+n9JKPqAKIzdLOrviDKr8uDxA/ZPucuAHYCScq3IuRNwgdzgOKOvlVVDW5+uObEWahKEQHs8e7zC4fKdscq5CsZhuY0rVV8G6UNW3Hj69OL7gefiQ5Bd88QoF0X2/CFPe+5GngehpbMnIAg8iH55pEC5v516w4zaij4lyUlcY/o9foSre8YJaD5UlkfsGCj5HJiOnPLCK6l1rtxVTbol4GYq8+w5kWQhfHzfTp4GzUZuQS12K32kynDt3EV0To3VPpbTxK4+Bdw5BnEo+gYaV9/ynM6BiCqlnNUWi42JzUwpC1MFiesVuEaZ/IgtXeZM9/vnp1WgKZDwqDNfvvv7l+DaLI4h+kx7cgSi6EQraxOLBMu/i76CAh6SXunHIKyIhIo1FbQJ8n2HohTZ6bD3jIbnJz/KEqNkeCyA="
    skip_cleanup: true
```

I started a new [build](https://travis-ci.org/fg2it/grafana-on-raspberry/builds/352699743)

**Comment by dismine** [comment]
Hi guys,

Looks like i have meet the [same problem](https://travis-ci.org/dismine/Valentina_git/jobs/352735632). Switching to branch dpl 1.8.47 did not help me.

**Comment by fg2it** [comment]
> I started a new [build](https://travis-ci.org/fg2it/grafana-on-raspberry/builds/352699743)

and it fails the same way

**Comment by adejanovski** [comment]
Hi folks,

I'm having the same issue here : https://api.travis-ci.org/v3/job/353266390/log.txt

The uploads started failing somewhere between March 6th (last working upload) and 12th (first failing upload).
After reaching out to Travis support, I tried downgrading to 1.8.47 : 

```
- provider: bintray
  edge:
    branch: v1.8.47
  file: src/ci/descriptor-rpm-beta.json
  user: adejanovski
  key:
    secure: "...
```

But I still get the same problem : 

```

HEAD is now at e6a53d8... Bump to 1.8.47

travis_time:end:2864cca6:start=1521025308374059195,finish=1521025308391135523,duration=17076328
[0Ktravis_time:start:00a841d8
[0K$ git show-ref -s HEAD
244c610bcc6b4e0d315fee4e21d67fe15e64594b

travis_time:end:00a841d8:start=1521025308399023101,finish=1521025308405980882,duration=6957781
[0Ktravis_time:start:11224ba8
[0K$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem build dpl.gemspec
WARNING:  pessimistic dependency on rspec (~> 3.0.0, development) may be overly strict
  if rspec is semantically versioned, use:
    add_development_dependency 'rspec', '~> 3.0', '>= 3.0.0'
WARNING:  open-ended dependency on rspec-its (>= 0, development) is not recommended
  if rspec-its is semantically versioned, use:
    add_development_dependency 'rspec-its', '~> 0'
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
WARNING:  open-ended dependency on coveralls (>= 0, development) is not recommended
  if coveralls is semantically versioned, use:
    add_development_dependency 'coveralls', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: dpl
  Version: 1.8.48.travis.1922.1
  File: dpl-1.8.48.travis.1922.1.gem

travis_time:end:11224ba8:start=1521025308412178288,finish=1521025309553184125,duration=1141005837
[0Ktravis_time:start:041a0111
[0K
travis_time:end:041a0111:start=1521025309572279864,finish=1521025309576443296,duration=4163432
[0Ktravis_time:start:07a98927
[0K$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install $TRAVIS_BUILD_DIR/dpl-*.gem --pre
Successfully installed dpl-1.8.48.travis.1922.1
1 gem installed

travis_time:end:07a98927:start=1521025309582718070,finish=1521025310979743209,duration=1397025139
[0Ktravis_fold:end:dpl_4
[0Ktravis_time:start:0f648433
[0Ktravis_fold:start:dpl.1
[33mInstalling deploy dependencies[0m

travis_fold:end:dpl.1
[Bintray Upload] Reading descriptor file: src/ci/descriptor-maven-snapshot.json
[Bintray Upload] Creating version '1.2.0-BETA-20180314'...
[Bintray Upload] Bintray response: 401 Unauthorized. This resource requires authentication
[Bintray Upload] Uploading file 'src/server/target/cassandra-reaper-1.2.0-BETA-20180314-javadoc.jar' to io/cassandrareaper/cassandra-reaper/1.2.0-BETA-20180314/cassandra-reaper-1.2.0-BETA-20180314-javadoc.jar
[Bintray Upload] Bintray response: 401 Unauthorized. This resource requires authentication
[Bintray Upload] Uploading file 'src/server/target/cassandra-reaper-1.2.0-BETA-20180314-sources.jar' to io/cassandrareaper/cassandra-reaper/1.2.0-BETA-20180314/cassandra-reaper-1.2.0-BETA-20180314-sources.jar
[Bintray Upload] Bintray response: 401 Unauthorized. This resource requires authentication
[Bintray Upload] Uploading file 'src/server/target/cassandra-reaper-1.2.0-BETA-20180314.jar' to io/cassandrareaper/cassandra-reaper/1.2.0-BETA-20180314/cassandra-reaper-1.2.0-BETA-20180314.jar
[Bintray Upload] Bintray response: 401 Unauthorized. This resource requires authentication
[Bintray Upload] Uploading file 'src/server/pom.xml' to io/cassandrareaper/cassandra-reaper/1.2.0-BETA-20180314/cassandra-reaper-1.2.0-BETA-20180314.pom
[Bintray Upload] Bintray response: 401 Unauthorized. This resource requires authentication
[Bintray Upload] Signing version with passphrase...
[Bintray Upload] Bintray response: 401 Unauthorized. This resource requires authentication
[Bintray Upload] Publishing version '1.2.0-BETA-20180314' of package 'cassandra-reaper'...
[Bintray Upload] Bintray response: 401 Unauthorized. This resource requires authentication
```

**Comment by BanzaiMan** [comment]
@adejanovski Could you point to a working deployment? Thanks.

**Comment by adejanovski** [comment]
Hi @BanzaiMan,

sure thing : https://travis-ci.org/thelastpickle/cassandra-reaper/jobs/349673544

```
travis_time:end:0fba799e:start=1520319507184204890,finish=1520319507191009382,duration=6804492
[0Ktravis_fold:end:before_deploy
[0Ktravis_fold:start:dpl.0
[0Ktravis_time:start:1c617440
[0K$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Successfully installed dpl-1.8.47
1 gem installed

travis_time:end:1c617440:start=1520319508189300287,finish=1520319509523239913,duration=1333939626
[0Ktravis_fold:end:dpl.0
[0Ktravis_time:start:00477b7f
[0Ktravis_fold:start:dpl.1
[33mInstalling deploy dependencies[0m

travis_fold:end:dpl.1
[Bintray Upload] Reading descriptor file: src/ci/descriptor-maven-snapshot.json
[Bintray Upload] Creating version '1.2.0-BETA-20180306'...
[Bintray Upload] Bintray response: 201 Created. 
[Bintray Upload] Adding attributes for version '1.2.0-BETA-20180306'...
[Bintray Upload] Bintray response: 200 OK. 
[Bintray Upload] Uploading file 'src/server/target/cassandra-reaper-1.2.0-BETA-20180306-javadoc.jar' to io/cassandrareaper/cassandra-reaper/1.2.0-BETA-20180306/cassandra-reaper-1.2.0-BETA-20180306-javadoc.jar
[Bintray Upload] Bintray response: 201 Created. success
[Bintray Upload] Uploading file 'src/server/target/cassandra-reaper-1.2.0-BETA-20180306-sources.jar' to io/cassandrareaper/cassandra-reaper/1.2.0-BETA-20180306/cassandra-reaper-1.2.0-BETA-20180306-sources.jar
[Bintray Upload] Bintray response: 201 Created. success
[Bintray Upload] Uploading file 'src/server/target/cassandra-reaper-1.2.0-BETA-20180306.jar' to io/cassandrareaper/cassandra-reaper/1.2.0-BETA-20180306/cassandra-reaper-1.2.0-BETA-20180306.jar
[Bintray Upload] Bintray response: 201 Created. success
[Bintray Upload] Uploading file 'src/server/pom.xml' to io/cassandrareaper/cassandra-reaper/1.2.0-BETA-20180306/cassandra-reaper-1.2.0-BETA-20180306.pom
[Bintray Upload] Bintray response: 201 Created. success
[Bintray Upload] Signing version with passphrase...
[Bintray Upload] Bintray response: 200 OK. success
[Bintray Upload] Publishing version '1.2.0-BETA-20180306' of package 'cassandra-reaper'...
[Bintray Upload] Bintray response: 200 OK. 
```

The interesting thing is that although I indicated 1.8.47 in my deploy config, the logs of the last job I ran indicate it's using 1.8.48.
The last successful job that ran on March 6th was indeed using 1.8.47.

**Comment by BanzaiMan** [comment]
@adejanovski Is the API key correct in the failing build? https://github.com/thelastpickle/cassandra-reaper/blob/8c9de3c83acbc6666e5cb12fccd2deee5b3b3d92/.travis.yml#L65

**Comment by adejanovski** [comment]
I just switched back to an "unsecure" api key that is stored in Travis private env variables and it's working again with 1.8.47/48 with : 

```
- provider: bintray
  edge:
    branch: v1.8.47
  file: src/ci/descriptor-tarball.json
  user: adejanovski
  key: $BINTRAY_API_KEY
  dry-run: false
  skip_cleanup: true
  on:
    tags: true
```
I think I had followed the steps to encrypt the key correctly though, but hey, it's working now : https://api.travis-ci.org/v3/job/353337207/log.txt

**Comment by BanzaiMan** [comment]
@dismine Your issue appears to be an incorrect deploy key.

**Comment by dismine** [comment]
@BanzaiMan, I already tried to switch the key to new. For appveyor it works, but travis again complains about the key. Plus my issue started not after the switch, but before it.

**Comment by BanzaiMan** [comment]
@dismine What switch are you talking about?

**Comment by dismine** [comment]
@BanzaiMan i mean change of the API key. This was my first guess. To try to revoke the old key and create new one. Again, for appveyor new key works, for travis doesn't.

**Comment by BanzaiMan** [comment]
@dismine I've double checked this value https://github.com/dismine/Valentina_git/blob/0a27af972d1b8988bcceeee6947028153f9bd7b6/.travis.yml#L98. It appears to start with `SOMEVAR=bedc…`, which I don't think is a correct value. Please try encrypting the correct key.

**Comment by spenserpothier** [comment]
This issue is affecting my team as well.
dpl 1.9 fails to authenticate with bintray [build 244](https://travis-ci.org/Nordstrom/xrpc/builds/351551104#L1105)
Changing to 1.8.47 succeeds [build 253](https://travis-ci.org/Nordstrom/xrpc/builds/353445518#L1141)
I have performed a few operations using the [bintray api](https://bintray.com/docs/api/#_content_uploading_publishing) using curl with the same API key specified in our travis-ci environment variables and those succeeded as well.

**Comment by BanzaiMan** [comment]
@fg2it https://github.com/travis-ci/travis-build/pull/1330 should fix the hang on the second (and subsequent) deploys.

**Comment by dismine** [comment]
@BanzaiMan thank you. I just fixed the key, but as with others, for me [it works](https://travis-ci.org/dismine/Valentina_git/jobs/353463180) only with branch 1.8.47.

**Comment by BanzaiMan** [comment]
@dismine Yes, we are aware of that; this is the issue to discuss it. The proposed fix is in the `bintray-unauth` branch, but I don't see that you've tested this. https://github.com/travis-ci/travis-ci/issues/9314#issuecomment-371945627

**Comment by fg2it** [comment]
@BanzaiMan awsome : this one [works](https://travis-ci.org/fg2it/grafana-on-raspberry/builds/353506634).

**Comment by BanzaiMan** [comment]
Sweet. I'll merge the PR, and have a 1.9.2 release before the end of the week.

**Comment by fg2it** [comment]
@BanzaiMan nice. Does it mean we will have to drop the
```yaml
  edge:
      branch: bintray-unauth
```

**Comment by BanzaiMan** [comment]
@fg2it Eventually. We'll keep the branch alive for a week or so after the 1.9.2 release, so that you can get off it.

**Comment by BanzaiMan** [comment]
1.9.2 is out.

**Comment by fg2it** [comment]
@BanzaiMan by the way, tested and working.
