### ISSUE TITLE
bug(deploy): Escape single quote for project-name option

### ISSUE THREAD

**Issue by Kristinita** [travis-ci/travis-ci#9325]
### 1. Summary

I can't escape single quote in value of [**`project-name` option**](https://docs.travis-ci.com/user/deployment/pages/#Further-configuration).

### 2. Configuration

See [**demo project configuration in `master` branch**](https://github.com/Kristinita/SashaTravis/tree/master) of my repository.

Part of my `.travis.yml`:

```yaml
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: SashaDest
  github-token: $GITHUB_API_KEY
  keep-history: true
  on:
    branch: master
  project-name: Kristinita's Search
  verbose: true
```

I want, that in commit messages display `Kristinita's Search`, but I can't do it.

### 3. Not helped

I try (see [**build history**](https://travis-ci.org/Kristinita/SashaTravis/builds)):

+ `Kristinita\'s Search`,
+ `Kristinita\\'s Search`,
+ `Kristinita''s Search`,
+ `"Kristinita's Search"`,
+ `Kristinita&#39;s Search`.

Not helped.

### 4. Do not offer

Please, do not offer, that I shouldn't use single quotes in project name.

Thanks.

**Comment by BanzaiMan** [comment]
The `project_name` value is passed to this line:

https://github.com/travis-ci/dpl/blob/244c610bcc6b4e0d315fee4e21d67fe15e64594b/lib/dpl/provider/pages.rb#L177

It looks to me that quoting would require another level of escaping; so, for example, this might work (untested):

```yaml
deploy:
  provider: pages
  project-name: Kristinita\\\'s Search
  ⋮
```

However, you are right, this (if it works at all) seems overly complex, and should be fixed on our side instead.

**Comment by Kristinita** [comment]
> The project_name value is passed to this line:

Maybe better make commit message, for example, as in [**this message**](https://github.com/travis-ci/travis-ci/issues/9287#issuecomment-372577006)?

Thanks.

**Comment by Kristinita** [comment]
The problem not solved at the time.

Thanks.

**Comment by Kristinita** [comment]
The problem not solved at the time.

Thanks.

**Comment by DrTorte** [comment]
Hello,

As we're no longer supporting GitHub issues but this issue remains open, I'm creating a copy of this on the forum. [Please see this link](https://travis-ci.community/t/issue-bug-deploy-escape-single-quote-for-project-name-option/1288).

Thanks and happy building!
