### ISSUE TITLE
Travis deploy library in Bintray. Build folder does not exist

### ISSUE THREAD

**Issue by baillyjamy** [travis-ci/travis-ci#9394]
I try to upload my library on Bintray after a build with Travis-ci. I followed [this tutorial][1] and read [the documentation][2].

But during the deployment phase I get the warning: <br>`[Bintray Upload] Warning: Path: build/libs/ does not exist.
`

My library is not deployed and I don't understand why travis can't find `build/libs`.
I checked with simple `ls` command in .travis.yml and the path is valid.

I am looking to send `.pom` and `.jar` files located in `build/libs` folder.
I use this path like this: <br>

      "files":
      [
        {
          "includePattern": "build/libs/(.*)",
          "uploadPattern": "com/baillyj/jikankt/1.0.0/$1"
        }
      ]

Is the syntax not good?

  [1]: https://techdev.io/en/developer-blog/how-to-publish-a-kotlin-library-to-bintray-using-gradle-and-travis-ci
  [2]: https://docs.travis-ci.com/user/deployment/bintray

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by baillyjamy** [comment]
I forgot, I'm sorry. You can find the build log [right here][1]

[1]: https://pastebin.com/eMt7V6C7

**Comment by mmatyas** [comment]
I'm having the same error, the Bintray deploy doesn't see a directory that clearly exists. [Here](https://travis-ci.org/mmatyas/pegasus-frontend/jobs/358401009)'s a build log, with the error:

```
Preparing deploy
[Bintray Upload] Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.
Saved working directory and index state WIP on (no branch): ebdabda Added support for next/previous page of games
sh: 0: getcwd() failed: No such file or directory
mv: cannot move ‘/home/travis/dpl’ to ‘.dpl’: No such file or directory

Deploying application
[Bintray Upload] Reading descriptor file: /home/travis/build/mmatyas/pegasus-frontend/etc/ci/bintray_travis.json
[Bintray Upload] Warning: Path: dist/ does not exist.
[Bintray Upload] Publishing version 'continuous' of package 'pegasus-frontend'...
[Bintray Upload] Bintray response: 200 OK. 
```

The same `travis.yml` and descriptor used to work at least a few weeks ago ([example](https://travis-ci.org/mmatyas/pegasus-frontend/jobs/348607246)):
```
Installing deploy dependencies
[Bintray Upload] Reading descriptor file: /home/travis/build/mmatyas/pegasus-frontend/etc/ci/bintray_travis.json
[Bintray Upload] Uploading file 'dist/pegasus-fe_alpha6-2-g64f2995_x11-static.zip' to /pegasus-fe_alpha6-2-g64f2995_x11-static.zip
[Bintray Upload] Bintray response: 201 Created. success
[Bintray Upload] Publishing version 'continuous' of package 'pegasus-frontend'...
[Bintray Upload] Bintray response: 200 OK. 
```

**Comment by BanzaiMan** [comment]
@baillyjamy In the logs, you see:

```
Preparing deploy
[Bintray Upload] Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.
Saved working directory and index state WIP on (no branch): d118b6d AZERTY
```

By default, we stash any changes to the directory before deploying. If your job is creating `build/libs` and the build artifacts are not in the git repository, you should add:

```yaml
deploy:
  skip_cleanup: true
```

to your configuration. This is explained in the docs link in the warning message above.

**Comment by BanzaiMan** [comment]
@mmatyas Your issue _appears_ to be a different manifestation of the same issue.

**Comment by BanzaiMan** [comment]
Ah, I understand now.

We released `dpl` 1.9.0 a couple of weeks ago. One thing we changed with that release is that we brought the `bintray` deployment code to be more in line with the rest of the code base.

With `dpl` 1.8.x, `bintray` basically ignored this option, but now it is necessary.

**Comment by baillyjamy** [comment]
Thanks for your support, I did not understand the purpose of the cleanup. Now it works.

**Comment by mmatyas** [comment]
I can also confirm it works now, thanks!

**Comment by QingYanL** [comment]
```
**$ ls**
Dockerfile
cita-cli
**cita-cli-x86_64-mac-osx-tls-0.19.4.tar.gz**
before_deploy.8
0.01s$ echo "before_deploy1 pwd:"
before_deploy1 pwd:
before_deploy.9
0.01s$ pwd
**/Users/travis/build/QingYanL/cita-cli/docker/release**
dpl_0
5.03s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Warning, new version of rvm available '1.29.10', you are using older version '1.29.8'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Successfully installed dpl-1.10.15
1 gem installed
7.70s
dpl.1
Installing deploy dependencies
Successfully installed faraday-0.15.4
Successfully installed sawyer-0.8.2
Successfully installed octokit-4.6.2
Successfully installed dpl-releases-1.10.15
4 gems installed
Logged in as liyanzi
Deploying to repo: QingYanL/cita-cli
Current tag is: 4.1
**/Users/travis/build/QingYanL/cita-cli/docker/release/*.tar.gz does not exist.**
Setting target_commitish to d48b66e722b139c447a9b64d531ed68527e8f7f3
dpl.2
Preparing deploy
```

I set deploy:
  skip_cleanup: true
but there still not exist
